[Main]
Left=0
Top=49
Width=624
Height=398
Image=
Moveable=0
Trans=0

[ItemAccept_Btn]
Left=540
Top=367
Width=67
Height=19
Font=12
HAlign=1
VAlign=1
LabelYOffset=3
Color=222,255,165
BorderColor=23,68,0
SelectColor=255,255,122
SelectBorderColor=150,50,50
OverColor=100,250,100
DisableColor=128,138,135
DisableBorderColor=23,68,0
Up=0
Down=1
Over=2
OverFrame=2
Trans=0
Image=\spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr
Label=NhËn vËt phÈm

[DeleteMail_Btn]
Left=440
Top=367
Width=67
Height=19
Font=12
HAlign=1
VAlign=1
LabelYOffset=3
Color=222,255,165
BorderColor=23,68,0
SelectColor=255,255,122
SelectBorderColor=150,50,50
OverColor=100,250,100
DisableColor=128,138,135
DisableBorderColor=23,68,0
Up=0
Down=1
Over=2
OverFrame=2
Trans=0
Image=\spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr
Label=Xãa th­

[DeleteAllMail_Btn]
Left=440
Top=367
Width=67
Height=19
Font=12
HAlign=1
VAlign=1
LabelYOffset=3
Color=222,255,165
BorderColor=23,68,0
SelectColor=255,255,122
SelectBorderColor=150,50,50
OverColor=100,250,100
DisableColor=128,138,135
DisableBorderColor=23,68,0
Up=0
Down=1
Over=2
OverFrame=2
Trans=0
Image=\spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr
Label=Xãa toµn bé

[AutoDeleteLable]
Left=307
Top=369
Width=110
Color=169,211,190
Text=Tù ®éng xãa trèng hép th­

[AutoDelete_Btn]
Left=290
Top=369
Width=14
Height=14
Up=0
Down=1
Trans=0
CheckBox=1
Image=\Spr\Ui3\ÏµÍ³Ñ¡Ïî\¶©ÔÄ´ò¹´°´Å¥.spr

[SelectAllMailLable]
Left=227
Top=369
Width=50
Color=169,211,190
Text=TÊt c¶

[SelectAllMail_Btn]
Left=210
Top=369
Width=14
Height=14
Up=0
Down=1
Trans=0
CheckBox=1
Image=\Spr\Ui3\ÏµÍ³Ñ¡Ïî\¶©ÔÄ´ò¹´°´Å¥.spr


[MailCountLable]
Left=27
Top=369
Width=100
Color=169,211,190
Text=Sè l­îng th­:

[MailCountValue]
Left=125
Top=369
Width=100
Color=169,211,190
Text=0/100


[MailList]
Left=7
Top=0
Width=229
Height=0

[MailListScroll]
Left=6
Top=44
Width=250
Height=315

[MailListScroll_ScrollBar]
Left=234
Top=0
Width=15
Height=315
Type=1
Min=0
Max=0
PageSize=1
SlideBegin=16
SlideEnd=296
Image=\Spr\Ui3\ÁÄÌìÌõ\ÁÄÌìÌõÖÐ²¿¸Ä.spr
RepeatImg=1

[MailListScroll_ScrollBar_Btn]
Left=0
Top=0
Width=15
Height=35
Up=0
Down=0
Over=0
OverFrame=0
Trans=0
Image=\spr\Ui4\common\ÍÏ¶¯Ìõ.spr

[MailFilterTitle]
Left=27
Top=16
Width=80
Height=16
Font=12
HAlign=0
Color=169,211,190
Text=Läc:

[MailFilterBg]
Left=60
Top=12
Width=155
Height=20
Image=\spr\Ui4\email\É¸Ñ¡¿ò.spr

[MailFilterBtn]
Left=60
Top=16
Width=155
Height=20
Font=12
Trans=0
Color=169,211,190
OverColor=225,255,255
SelectColor=225,213,43

[MailFilterMenu]
MenuItemCount=4
MenuText1=Toµn bé th­
MenuText2=Th­ ch­a ®äc
MenuText3=Cã ®Ýnh kÌm
MenuText4=Th­ hÖ thèng
;MenuText5=ÅÄÂôÐÐÕÆ¹ñ