[Main]
Left=263
Top=2
Width=348
Height=345

[MailBigTitleValue]
Left=0
Top=15
Width=220
Height=24
Color=202,230,171
Font=14
Text=Th­ xin lçi tr× ho·n b¶o tr×

[MailSendTime]
Left=226
Top=15
Width=120
Height=24
Color=202,230,171
Font=12
Text=201905013132

[MailSenderLable]
Left=0
Top=51
Width=65
Height=16
Color=0,255,0
Font=12
Text=Ng­êi göi:

[MailTitleLable]
Left=0
Top=70
Width=65
Height=14
Color=0,255,0
Font=12
Text=Tiªu ®Ò:

[MailSenderValue]
Left=66
Top=51
Width=275
Height=16
Color=202,230,171
Font=14
Text=Th­ hÖ thèng

[MailTitleValue]
Left=66
Top=70
Width=275
Height=14
Color=202,230,171
Font=14
Text=Th­ xin lçi tr× ho·n b¶o tr×

[DividingLine]
Left=4
Top=92
Width=228
Height=2
Image=spr\Ui4\email\ÐÅ¼þÄÚÈÝ·Ö¸îÏß.spr
NoMsg=1

[MailContentLable]
Left=0
Top=110
Width=140
Height=14
Color=0,255,0
Font=12
Text=Néi dung:

[MailContentValue]
Left=0
Top=130
Width=340
Height=185
Font=14
HAlign=0
;VAlign=1
MultiLine=1
Color=202,230,171


[MailAwardPos]
Left=300
Top=315
Interval=28

