[Main]
Adjust=M
Left=316
Top=231
Image=\Spr\Ui3\SpringGame\makehost.spr
Moveable=1
Trans=1

[GameClassTxt]
Left=10
Top=35
Width=100
Height=15
Font=12
Color=255,237,165
Text=Trﬂ ch¨i

[GameClass_0]
Left=64
Top=35
Width=53
Height=13
HAlign=1
VAlign=1
LabelXOffset=8
Font=12
Color=169,211,190
OverColor=169,211,190
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=1
DisableFrame=2
Over=0
Trans=0
Image=\Spr\Ui3\œµÕ≥—°œÓ\∂©‘ƒ¥Úπ¥∞¥≈•.spr
Label=B«u cua

[GameClass_1]
Left=120
Top=35
Width=53
Height=13
HAlign=1
VAlign=1
LabelXOffset=8
Font=12
Color=169,211,190
OverColor=169,211,190
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=1
DisableFrame=2
Over=0
Trans=0
Image=\Spr\Ui3\œµÕ≥—°œÓ\∂©‘ƒ¥Úπ¥∞¥≈•.spr
Label=Tµi xÿu

[HostCoinTxt]
Left=10
Top=59
Width=100
Height=15
Font=12
Color=255,237,165
Text=SË ti“n

[HostCoin]
Left=89
Top=59
Width=82
Height=15
Font=14
HAlign=1
VAlign=1
Color=22,15,9
BorderColor=227,255,212

[MinBetCoinTxt]
Left=10
Top=83
Width=100
Height=15
Font=12
Color=255,237,165
Text=ß∆t tËi thi”u

[MinBetCoin]
Left=89
Top=83
Width=82
Height=15
Font=14
HAlign=1
VAlign=1
Color=22,15,9
BorderColor=227,255,212

[MaxBetCoinTxt]
Left=10
Top=107
Width=100
Height=15
Font=12
Color=255,237,165
Text=ß∆t tËi Æa

[MaxBetCoin]
Left=89
Top=107
Width=82
Height=15
Font=14
HAlign=1
VAlign=1
Color=22,15,9
BorderColor=227,255,212

;»∑»œ∞¥≈•
[btnOk]
Left=4
Top=136
Width=74
Height=18
Up=0
Down=1
Over=2
OverFrame=2
NoOverSound=0
SendHoldMsg=0
Image=\Spr\Ui3\√‹¬Î…Ë∂®\»∑∂®.spr

;»°œ˚∞¥≈•
[btnClose]
Left=90
Top=136
Width=74
Height=18
Up=0
Down=1
Over=2
OverFrame=2
NoOverSound=0
SendHoldMsg=0
Image=\Spr\Ui3\UiChooseFace\CloseBtn.spr