; --------------------------------------------------------
; PET UI reference
; --------------------------------------------------------

[Main]
Left=130
Top=100
Width=517
Height=474
Moveable=1
Image=\Spr\Ui4\uipet\main.spr
ScriptFile=\\script\\vng_feature\\petsys\\pet_c.lua

[Img_Bg]
Left=-4
Top=-49
Width=600
Height=474
Image=\Spr\Ui4\uipet\Img_Bg.spr
; PET UI reference
Disable=1

[SlotImg_0]
Left=250
Top=50
Width=36
Height=36

[SlotImg_1]
Left=300
Top=50
Width=36
Height=36

[SlotImg_2]
Left=350
Top=50
Width=36
Height=36

[SlotImg_3]
Left=400
Top=50
Width=36
Height=36

[SlotImg_4]
Left=450
Top=50
Width=36
Height=36

[PassiveSlotImg_0]
Left=250
Top=100
Width=36
Height=36

[PassiveSlotImg_1]
Left=300
Top=100
Width=36
Height=36

[Img_Appearance]
Left=120
Top=350
Width=120
Height=200

[Btn_Close]
Left=200
Top=395
Width=110
Height=26
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\Btn.spr
Label= Đóng
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[Btn_Fusion]
Left=250
Top=170
Width=110
Height=20
Label=Hợp thể
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\Btn.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[Btn_Upgrade]
Left=375
Top=170
Width=110
Height=20
Label=Thăng Cấp
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\Btn.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[Btn_Rename]
Left=250
Top=195
Width=110
Height=20
Label=Đổi tên
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\Btn.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[Btn_Exp]
Left=375
Top=195
Width=110
Height=20
Label=Truyền EXP
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\Btn.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[Btn_Summon]
Left=250
Top=220
Width=110
Height=20
Label=Gọi ra
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\Btn.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[Btn_Unsummon]
Left=375
Top=220
Width=110
Height=20
Label=Thu hồi
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\Btn.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[Txt_Upgrade_Point_Title]
Left=10
Top=30
Width=160
Height=20
Text=Điểm thăng cấp
Font=14
Color=255,255,255

[Txt_Upgrade_Point]
Left=140
Top=30
Width=80
Height=20
Color=255,217,78

[Txt_Grown_Point_Title]
Left=10
Top=50
Width=160
Height=20
Text=Điểm trưởng thành
Color=255,255,255

[Txt_Grown_Point]
Left=140
Top=50
Width=80
Height=20
Color=255,217,78

[Txt_Tame_Point_Title]
Left=10
Top=70
Width=160
Height=20
Text=Điểm luyện hóa
Color=255,255,255

[Txt_Tame_Point]
Left=140
Top=70
Width=80
Height=20
Color=255,217,78

[Txt_Xiuwei_Point]
Left=140
Top=90
Width=80
Height=20
Color=255,217,78

[Txt_Xiuwei_Point_Title]
Left=10
Top=90
Width=160
Height=20
Text=Điểm tu dưỡng
Color=255,255,255

[Txt_LianGu_Point]
Left=140
Top=110
Width=80
Height=20
Color=255,217,78

[Txt_LianGu_Point_Title]
Left=10
Top=110
Width=160
Height=20
Text=Điểm Luyện Cốt:
Color=255,255,255

[Txt_Name_Title]
Left=10
Top=130
Width=120
Height=20
Text=Tên:
Color=255,255,255

[Txt_Name]
Left=80
Top=130
Width=160
Height=20
Color=255,217,78

[Txt_Level_Title]
Left=10
Top=150
Width=120
Height=20
Text=Đẳng cấp:
Color=255,255,255

[Txt_Level]
Left=80
Top=150
Width=160
Height=20
Color=255,217,78

[Txt_AttrAnti_Title]
Left=150
Top=150
Width=120
Height=20
Text=Kháng tất cả:
Color=255,255,255

[Txt_AttrAnti]
Left=230
Top=150
Width=160
Height=20
Color=255,217,78

[Txt_AttrStr_Title]
Left=10
Top=180
Width=95
Height=20
Text=Sức mạnh:
Color=255,255,255

[Txt_AttrStr]
Left=80
Top=180
Width=50
Height=20
Color=255,217,78


[Txt_AttrDex_Title]
Left=150
Top=180
Width=95
Height=20
Text=Thân pháp:
Color=255,255,255

[Txt_AttrDex]
Left=230
Top=180
Width=50
Height=20
Color=255,217,78

[Txt_AttrVit_Title]
Left=10
Top=210
Width=95
Height=20
Text=Sinh khí:
Color=255,255,255

[Txt_AttrVit]
Left=80
Top=210
Width=50
Height=20
Color=255,217,78

[Txt_AttrEng_Title]
Left=150
Top=210
Width=95
Height=20
Text=Nội công:
Color=255,255,255

[Txt_AttrEng]
Left=230
Top=210
Width=50
Height=20
Color=255,217,78

[Txt_Panel_Title]
Left=200
Top=-45
Width=80
Height=20
Font=16
Color=255,255,255
Text=Thú nuôi

[Txt_Skill_Title]
Left=340
Top=25
Width=100
Height=20
Font=16
Color=255,255,255
Text=Kỹ năng

[Txt_Operation_Title]
Left=330
Top=140
Width=150
Height=20
Font=16
Color=255,255,255
Text=Thao tác thú nuôi

[CompanionBtn]
Left=400
Top=352
Color=255,255,255
SelectColor=255,237,16
OverColor=255,23,165
Font=12
LabelYOffset=8
DisableFrame=3
Image=\spr\Ui4\uipet\btn_medium.spr
Label=Đúc lại

[CompanionUpgradeBtn]
Left=300
Top=352
Color=255,255,255
SelectColor=255,237,16
OverColor=255,23,165
Font=12
LabelYOffset=8
DisableFrame=3
Image=\spr\Ui4\uipet\btn_medium.spr
Label=thăng cấp

[Equip_1]
Left=250
Top=256
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[Equip_2]
Left=295
Top=256
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[Equip_3]
Left=340
Top=256
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[Equip_4]
Left=385
Top=256
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[Equip_5]
Left=430
Top=256
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[Equip_6]
Left=250
Top=296
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[Equip_7]
Left=295
Top=296
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[Equip_8]
Left=340
Top=296
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[Equip_9]
Left=385
Top=296
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[Equip_10]
Left=430
Top=296
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr

[EquipWeapon]
Left=255
Top=261
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0

[EquipArmor]
Left=300
Top=261
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0

[EquipRing]
Left=345
Top=261
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0

[EquipCuff]
Left=390
Top=261
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0

[EquipAmulet]
Left=435
Top=261
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0

[EquipBelt]
Left=255
Top=301
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0

[EquipPendant]
Left=300
Top=301
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0

[EquipBoot]
Left=345
Top=301
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0

[EquipSachet]
Left=395
Top=301
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0

[EquipHelm]
Left=435
Top=301
Width=40
Height=40
EnableClickEmpty=1
BGSpriteColor=110,110,0
HaveBgColor=0
;==============================================================================
