; --------------------------------------------------------
; PET skill UI reference
; --------------------------------------------------------

[Main]
Left=210
Top=150
Width=430
Height=365
Moveable=1
ScriptFile=\\script\\vng_feature\\petsys\\pet_c.lua
BindBtnBindTxt=Khóa
BindBtnBindedTxt=Mở khóa
Image=\Spr\Ui4\uipet\Playerportraitbottom.spr

[PassiveSkill_0]
Left=154
Top=250
Width=36
Height=36

[PassiveSkill_1]
Left=234
Top=250
Width=36
Height=36

[SkillLock_0]
Left=62
Top=100
Width=21
Height=23
Image=\spr\lock\lock.spr

[SkillLock_1]
Left=137
Top=100
Width=21
Height=23
Image=\spr\lock\lock.spr

[SkillLock_2]
Left=217
Top=100
Width=21
Height=23
Image=\spr\lock\lock.spr

[SkillLock_3]
Left=297
Top=100
Width=21
Height=23
Image=\spr\lock\lock.spr

[SkillLock_4]
Left=377
Top=100
Width=21
Height=23
Image=\spr\lock\lock.spr

[Skill_0]
Left=40
Top=80
Width=36
Height=36

[Skill_1]
Left=115
Top=80
Width=36
Height=36

[Skill_2]
Left=195
Top=80
Width=36
Height=36

[Skill_3]
Left=275
Top=80
Width=36
Height=36

[Skill_4]
Left=355
Top=80
Width=36
Height=36

[BindBtn_0]
Left=20
Top=130
Width=70
Height=25
Label=Khóa
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[BindBtn_1]
Left=100
Top=130
Width=74
Height=26
Label=Khóa
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0


[BindBtn_2]
Left=180
Top=130
Width=74
Height=26
Label=Khóa
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[BindBtn_3]
Left=260
Top=130
Width=74
Height=26
Label=Khóa
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[BindBtn_4]
Left=340
Top=130
Width=74
Height=26
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Label=Khóa
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[UpgradePassiveBtn_0]
Left=138
Top=300
Width=70
Height=25
Label=thăng cấp
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[UpgradePassiveBtn_1]
Left=218
Top=300
Width=74
Height=26
Label=thăng cấp
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[UpgradeBtn_0]
Left=20
Top=160
Width=70
Height=25
Label=thăng cấp
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[UpgradeBtn_1]
Left=100
Top=160
Width=74
Height=26
Label=thăng cấp
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0


[UpgradeBtn_2]
Left=180
Top=160
Width=74
Height=26
Label=thăng cấp
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[UpgradeBtn_3]
Left=260
Top=160
Width=74
Height=26
Label=thăng cấp
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[UpgradeBtn_4]
Left=340
Top=160
Width=74
Height=26
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\wordbig.spr
Label=thăng cấp
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[LearnPassiveSkillBtn]
Left=160
Top=333
Width=110
Height=26
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\smallbutton.spr
Label=Học kỹ năng
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[LearnSkillBtn]
Left=160
Top=195
Width=110
Height=26
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\smallbutton.spr
Label=Học kỹ năng
Font=14
LabelYOffset=4
Color=218,165,105
OverColor=225,213,43
SelectColor=255,253,122
SelectBorderColor=255,0,0

[BtnClose]
Left=395
Top=3
Width=20
Height=20
Up=0
Down=2
Over=3
OverFrame=1
Trans=0
Image=\spr\Ui4\common\close.spr

[Txt_Panel_Title]
Left=130
Top=2
Width=200
Height=20
Font=16
Color=255,255,255
Text=Kỹ năng thú nuôi
