[Main]
Adjust=M
Left=110
Top=89
Width=579
Height=421
Moveable=1
Image=\spr\Ui3\SpringGame\springgame.spr

[GameBkg]
Left=19
Top=33
GameBkg_0=\spr\Ui3\SpringGame\baucua.spr
GameBkg_1=\spr\Ui3\SpringGame\taixiu.spr

[btnClose]
Left=18
Top=397
Width=543
Height=21
Up=0
Down=1
Over=2
OverFrame=2
CheckBox=0
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\ÆæÕä¸ó¹Ø±Õ°´¼ü_vn.spr

[MakeHostBtn]
Left=55
Top=360
Width=149
Height=25
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=169,211,190
OverColor=124,255,125
SelectColor=77,77,77
DisableColor=77,77,77
Up=0
Down=1
Over=2
Trans=0
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\Í¨ÓÃ³¤°´¼ü.spr
Label=Lµm nhµ c¸i

[HostGetCoinBtn]
Left=55
Top=360
Width=149
Height=25
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=169,211,190
OverColor=124,255,125
SelectColor=77,77,77
DisableColor=77,77,77
Up=0
Down=1
Over=2
Trans=0
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\Í¨ÓÃ³¤°´¼ü.spr
Label=Nh­êng c¸i

[GetLastCoinBtn]
Left=55
Top=360
Width=149
Height=25
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=169,211,190
OverColor=124,255,125
SelectColor=77,77,77
DisableColor=77,77,77
Up=0
Down=1
Over=2
Trans=0
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\Í¨ÓÃ³¤°´¼ü.spr
Label=NhËn l¹i Xu

[HostNameTxt]
Left=40
Top=235
Width=56
Height=14
Font=14
Color=255,237,165
Text=Nhµ c¸i

[HostName]
Left=140
Top=235
Width=120
Height=14
Font=14
Color=34,228,36

[HostRestTimeTxt]
Left=40
Top=255
Width=120
Height=14
Font=14
Color=255,237,165
Text=Sè l­ît

[HostRestTime]
Left=140
Top=255
Width=120
Height=14
Font=14
HAlign=0
Color=34,228,36
OverColor=255,217,78
OverBorderColor=200,0,0
SelColor=255,253,122
SelBorderColor=255,0,0

[HostCoinTxt]
Left=40
Top=275
Width=120
Height=14
Font=14
Color=255,237,165
Text=Xu nhµ c¸i

[HostCoin]
Left=140
Top=275
Width=120
Height=14
Font=14
HAlign=0
Color=34,228,36
OverColor=255,217,78
OverBorderColor=200,0,0
SelColor=255,253,122
SelBorderColor=255,0,0

[MinBetCoinTxt]
Left=40
Top=295
Width=120
Height=14
Font=14
Color=255,237,165
Text=§Æt tèi thiÓu

[MinBetCoin]
Left=140
Top=295
Width=120
Height=14
Font=14
HAlign=0
Color=34,228,36
OverColor=255,217,78
OverBorderColor=200,0,0
SelColor=255,253,122
SelBorderColor=255,0,0

[MaxBetCoinTxt]
Left=40
Top=315
Width=120
Height=14
Font=14
Color=255,237,165
Text=§Æt tèi ®a

[MaxBetCoin]
Left=140
Top=315
Width=120
Height=14
Font=14
HAlign=0
Color=34,228,36
OverColor=255,217,78
OverBorderColor=200,0,0
SelColor=255,253,122
SelBorderColor=255,0,0

[CoinTxt]
Left=40
Top=340
Width=120
Height=14
Font=14
Color=255,237,165
Text=Xu b¶n th©n

[Coin]
Left=140
Top=340
Width=120
Height=14
Font=14
Color=255,17,78
;BorderColor=255,0,0

[Dice]
Dice_0=\spr\Ui3\SpringGame\xucxacbaucua.spr
Dice_1=\spr\Ui3\SpringGame\xucxactaixiu.spr

[Dice_0]
Left=40
Top=66
Width=54
Height=54
Moveable=0

[Dice_1]
Left=101
Top=66
Width=54
Height=54
Moveable=0

[Dice_2]
Left=162
Top=66
Width=54
Height=54
Moveable=0

[BetBtn_0]
Left=243
Top=173
Width=53
Height=20
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\Í¨ÓÃ°´¼ü.spr
Label=§Æt
Color=169,211,190
OverColor=124,255,125
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=1
DisableFrame=2
Over=2
OverFrame=2
Font=12
LabelYOffset=4
HAlign=1
[BetBtn_1]
Left=348
Top=173
Width=53
Height=20
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\Í¨ÓÃ°´¼ü.spr
Label=§Æt
Color=169,211,190
OverColor=124,255,125
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=1
DisableFrame=2
Over=2
OverFrame=2
Font=12
LabelYOffset=4
HAlign=1
[BetBtn_2]
Left=454
Top=173
Width=53
Height=20
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\Í¨ÓÃ°´¼ü.spr
Label=§Æt
Color=169,211,190
OverColor=124,255,125
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=1
DisableFrame=2
Over=2
OverFrame=2
Font=12
LabelYOffset=4
HAlign=1
[BetBtn_3]
Left=243
Top=347
Width=53
Height=20
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\Í¨ÓÃ°´¼ü.spr
Label=§Æt
Color=169,211,190
OverColor=124,255,125
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=1
DisableFrame=2
Over=2
OverFrame=2
Font=12
LabelYOffset=4
HAlign=1
[BetBtn_4]
Left=348
Top=347
Width=53
Height=20
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\Í¨ÓÃ°´¼ü.spr
Label=§Æt
Color=169,211,190
OverColor=124,255,125
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=1
DisableFrame=2
Over=2
OverFrame=2
Font=12
LabelYOffset=4
HAlign=1
[BetBtn_5]
Left=454
Top=347
Width=53
Height=20
Image=\spr\Ui3\ÂòÂô\ÐÂÆæÕä¸ó½çÃæ\Í¨ÓÃ°´¼ü.spr
Label=§Æt
Color=169,211,190
OverColor=124,255,125
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=1
DisableFrame=2
Over=2
OverFrame=2
Font=12
LabelYOffset=4
HAlign=1

[InfoText]
Left=40
Top=120
Width=180
Height=75
Font=14
MsgColor=255,255,0
;BorderColor=255,0,0

[SpringNo]
Left=140
Top=195
Width=120
Height=20
Font=14
;HAlign=1
Color=255,217,78
BorderColor=200,0,0

[SpringNoTxt]
Left=40
Top=195
Width=120
Height=14
Font=14
Color=255,237,165
Text=M· trËn

[RemainTime]
Left=140
Top=215
Width=120
Height=20
Font=14
;HAlign=1
Color=255,217,78
BorderColor=200,0,0

[RemainTxt]
Left=40
Top=215
Width=120
Height=14
Font=14
Color=255,237,165
Text=TiÕn ®é

[CoinShadow_0]
Left=296
Top=175
Width=40
Height=15
ShadowColor=150,150,150
ShadowColorAlpha=128

[CoinInput_0]
Left=298
Top=175
Width=50
Height=13
Font=14
HAlign=1
VAlign=1
Type=1
MultiLine=0
MaxLen=8
Color=255,255,255


BorderColor=0,0,0
FocusBkColor=180,40,40
FocusBkColorAlpha=80
[CoinShadow_1]
Left=401
Top=175
Width=40
Height=15
ShadowColor=150,150,150
ShadowColorAlpha=128

[CoinInput_1]
Left=403
Top=175
Width=50
Height=13
Font=14
HAlign=1
VAlign=1
Type=1
MultiLine=0
MaxLen=8
Color=255,255,255


BorderColor=0,0,0
FocusBkColor=180,40,40
FocusBkColorAlpha=80
[CoinShadow_2]
Left=507
Top=175
Width=40
Height=15
ShadowColor=150,150,150
ShadowColorAlpha=128

[CoinInput_2]
Left=509
Top=175
Width=50
Height=13
Font=14
HAlign=1
VAlign=1
Type=1
MultiLine=0
MaxLen=8
Color=255,255,255


BorderColor=0,0,0
FocusBkColor=180,40,40
FocusBkColorAlpha=80
[CoinShadow_3]
Left=296
Top=349
Width=40
Height=15
ShadowColor=150,150,150
ShadowColorAlpha=128

[CoinInput_3]
Left=298
Top=349
Width=50
Height=13
Font=14
HAlign=1
VAlign=1
Type=1
MultiLine=0
MaxLen=8
Color=255,255,255


BorderColor=0,0,0
FocusBkColor=180,40,40
FocusBkColorAlpha=80
[CoinShadow_4]
Left=401
Top=349
Width=40
Height=15
ShadowColor=150,150,150
ShadowColorAlpha=128

[CoinInput_4]
Left=403
Top=349
Width=50
Height=13
Font=14
HAlign=1
VAlign=1
Type=1
MultiLine=0
MaxLen=8
Color=255,255,255


BorderColor=0,0,0
FocusBkColor=180,40,40
FocusBkColorAlpha=80
[CoinShadow_5]
Left=507
Top=349
Width=40
Height=15
ShadowColor=150,150,150
ShadowColorAlpha=128

[CoinInput_5]
Left=509
Top=349
Width=50
Height=13
Font=14
HAlign=1
VAlign=1
Type=1
MultiLine=0
MaxLen=8
Color=255,255,255

BorderColor=0,0,0
FocusBkColor=180,40,40
FocusBkColorAlpha=80
[LastTotalCoinTxt_0]
Left=240
Top=36
Width=48
Height=20
Font=12
HAlign=0
Color=255,237,165
Text=Tr­íc:
[LastTotalCoin_0]
Left=275
Top=36
Width=66
Height=20
Font=12
HAlign=0
Color=255,237,165
[FeedRate_0]
Left=275
Top=56
Width=46
Height=20
Font=12
HAlign=2
Color=255,237,165
[BetTotalCoinTxt_0]
Left=245
Top=133
Width=60
Height=20
Font=12
HAlign=0
Color=255,217,78
BorderColor=200,0,0
Text=Tæng:
[BetTotalCoin_0]
Left=245
Top=133
Width=75
Height=20
Font=12
HAlign=2
Color=255,217,78
BorderColor=200,0,0

[BetCoin_0]
Left=253
Top=157
Width=60
Height=20
Font=14
HAlign=1
Color=255,217,78
BorderColor=200,0,0

[LastTotalCoinTxt_1]
Left=345
Top=36
Width=48
Height=20
Font=12
HAlign=0
Color=255,237,165
Text=Tr­íc:
[LastTotalCoin_1]
Left=380
Top=36
Width=66
Height=20
Font=12
HAlign=0
Color=255,237,165
[FeedRate_1]
Left=380
Top=56
Width=46
Height=20
Font=12
HAlign=2
Color=255,237,165
[BetTotalCoinTxt_1]
Left=350
Top=133
Width=60
Height=20
Font=12
HAlign=0
Color=255,217,78
BorderColor=200,0,0
Text=Tæng:
[BetTotalCoin_1]
Left=350
Top=133
Width=75
Height=20
Font=12
HAlign=2
Color=255,217,78
BorderColor=200,0,0

[BetCoin_1]
Left=359
Top=157
Width=60
Height=20
Font=14
HAlign=1
Color=255,217,78
BorderColor=200,0,0

[LastTotalCoinTxt_2]
Left=450
Top=36
Width=48
Height=20
Font=12
HAlign=0
Color=255,237,165
Text=Tr­íc:
[LastTotalCoin_2]
Left=485
Top=36
Width=66
Height=20
Font=12
HAlign=0
Color=255,237,165
[FeedRate_2]
Left=485
Top=56
Width=46
Height=20
Font=12
HAlign=2
Color=255,237,165
[BetTotalCoinTxt_2]
Left=456
Top=133
Width=60
Height=20
Font=12
HAlign=0
Color=255,217,78
BorderColor=200,0,0
Text=Tæng:
[BetTotalCoin_2]
Left=456
Top=133
Width=75
Height=20
Font=12
HAlign=2
Color=255,217,78
BorderColor=200,0,0

[BetCoin_2]
Left=465
Top=157
Width=60
Height=20
Font=14
HAlign=1
Color=255,217,78
BorderColor=200,0,0

[LastTotalCoinTxt_3]
Left=240
Top=211
Width=48
Height=20
Font=12
HAlign=0
Color=255,237,165
Text=Tr­íc:
[LastTotalCoin_3]
Left=275
Top=211
Width=66
Height=20
Font=12
HAlign=0
Color=255,237,165
[FeedRate_3]
Left=275
Top=231
Width=46
Height=20
Font=12
HAlign=2
Color=255,237,165
[BetTotalCoinTxt_3]
Left=245
Top=308
Width=60
Height=20
Font=12
HAlign=0
Color=255,217,78
BorderColor=200,0,0
Text=Tæng:
[BetTotalCoin_3]
Left=245
Top=308
Width=75
Height=20
Font=12
HAlign=2
Color=255,217,78
BorderColor=200,0,0

[BetCoin_3]
Left=253
Top=331
Width=60
Height=20
Font=14
HAlign=1
Color=255,217,78
BorderColor=200,0,0

[LastTotalCoinTxt_4]
Left=345
Top=211
Width=48
Height=20
Font=12
HAlign=0
Color=255,237,165
Text=Tr­íc:
[LastTotalCoin_4]
Left=380
Top=211
Width=66
Height=20
Font=12
HAlign=0
Color=255,237,165
[FeedRate_4]
Left=380
Top=231
Width=46
Height=20
Font=12
HAlign=2
Color=255,237,165
[BetTotalCoinTxt_4]
Left=350
Top=308
Width=60
Height=20
Font=12
HAlign=0
Color=255,217,78
BorderColor=200,0,0
Text=Tæng:
[BetTotalCoin_4]
Left=350
Top=308
Width=75
Height=20
Font=12
HAlign=2
Color=255,217,78
BorderColor=200,0,0

[BetCoin_4]
Left=359
Top=331
Width=60
Height=20
Font=14
HAlign=1
Color=255,217,78
BorderColor=200,0,0

[LastTotalCoinTxt_5]
Left=450
Top=211
Width=48
Height=20
Font=12
HAlign=0
Color=255,237,165
Text=Tr­íc:
[LastTotalCoin_5]
Left=485
Top=211
Width=66
Height=20
Font=12
HAlign=0
Color=255,237,165
[FeedRate_5]
Left=485
Top=231
Width=46
Height=20
Font=12
HAlign=2
Color=255,237,165
[BetTotalCoinTxt_5]
Left=456
Top=308
Width=60
Height=20
Font=12
HAlign=0
Color=255,217,78
BorderColor=200,0,0
Text=Tæng:
[BetTotalCoin_5]
Left=456
Top=308
Width=75
Height=20
Font=12
HAlign=2
Color=255,217,78
BorderColor=200,0,0

[BetCoin_5]
Left=465
Top=331
Width=60
Height=20
Font=14
HAlign=1
Color=255,217,78
BorderColor=200,0,0
