[Main]
Left=470
Top=542
Width=131
Height=23
Moveable=1
Image=\Spr\Ui3\NewUI\ToolBar6.spr
Button0=Run
Button1=Sit
Button2=Horse
Button3=Exchange
Button4=PK
Button5=Rec

; Run button
[Run]
Left=23
Top=2
Width=20
Height=20
Image=\Spr\Ui3\Buttons\Btn_Run.spr
CheckBox=1
Up=0
Down=1
Trans=0
Tip=§i / Ch¹y (R)
ClassType=Player_Run

; Sit button
[Sit]
Left=2
Top=2
Width=20
Height=20
Image=\Spr\Ui3\Buttons\Btn_Sit.spr
CheckBox=1
Up=0
Down=1
Trans=0
Tip=Ngåi thiÒn (V)
ClassType=Player_Sit

; Horse button
[Horse]
Left=44
Top=2
Width=20
Height=20
Trans=0
Image=\Spr\Ui3\Buttons\Btn_Horse.spr
CheckBox=1
Up=0
Down=1
Trans=0
Tip=Lªn / Xuèng ngùa (M)
ClassType=Player_Horse

; Exchange button
[Exchange]
Left=65
Top=2
Width=20
Height=20
Trans=0
Image=\Spr\Ui3\Buttons\Btn_Exchange.spr
CheckBox=1
Up=0
Down=1
Tip=Më Giao dÞch
ClassType=Player_Exchange

; PK button
[PK]
Left=108
Top=2
Width=20
Height=20
Trans=0
Image=\Spr\Ui3\Buttons\Btn_PK.spr
Up=0
Down=1
CheckBox=1
Tip=§ãng / Më PK
ClassType=Player_PK

; Recorder button
[Rec]
Left=87
Top=2
Width=20
Height=20
Trans=0
Image=\Spr\Ui3\Buttons\Btn_Rec.spr
Tip=Ghi h×nh
ClassType=Player_Recorder
