[Main]
Left=300
Top=53
Width=223
Height=449
Moveable=1
StartPos=485.0
Trans=1
Image=\Spr\Ui3\UiShop\main.spr

[Title]
Left=0
Top=7
Width=215
Height=24
Font=16
HAlign=1
VAlign=0
Color=255,253,122
Text=Hµnh Trang Më Réng
;BorderColor=255,0,0
DummyWnd=1

[CloseBtn]
Left=197
Top=3
Image=\spr\ui3\UiItem\close.spr
Font=12
Width=24
Height=24
Color=200,200,200
;Label=§ãng (ESC)
Tip=PhÝm t¾t: <color=green>ESC<color>
Up=0
Down=1
Over=2
OverFrame=2

[ItemBox]
Left=10
Top=32
Width=203
Height=348
HUnits=7
VUnits=12
UnitBorder=2

[Settings]
BGBorderColor=100,80,30
BGSpriteColor=243,194,70
BGPurpleColor=188,40,255
BGPurpleBorder=100,80,123

[TextBtn]
Left=53
Top=345
Width=110
Height=18
Font=14
HAlign=0
Color=190,241,125
OverColor=204,204,204
SelColor=255,252,178
;OverBorderColor=255,0,0
;SelBgColor=140,121,99

[OpenExItem]
Left=11
Top=385
Width=150
Height=16
Font=14
Up=0
Down=1
CheckBox=1
Trans=0
Color=255,255,255
LabelXOffset=10
LabelYOffset=3
Label=më cïng hµnh trang
Image=\spr\vng\¹´Ñ¡¿ò_0.spr
Tip=më cïng víi hµnh trang


[AutoSortBtn]
Left=8
Top=418
Width=67
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,255,255
Over=1
Image=\Spr\Ui3\UiStoreBox\btn_xepdo.spr
; Label=XÕp ®å
Tip=Xö lý x¾p sÕp

[AutoCollectStackBtn]
Left=78
Top=418
Width=67
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,255,255
Over=1
Image=\spr\Ui3\UiExpandItem\btn_stack.spr
; Label=Gom Stack
Tip=Gom tÊt c¶ vËt phÈm cã thÓ xÕp chång tõ hµnh trang vÒ r­¬ng nµy

[AutoCollectLagBtn]
Left=148
Top=418
Width=67
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,255,255
Over=1
Image=\spr\ui3\UiExpandItem\btn_lag.spr
; Label=Gom Lag
Tip=Gom tÊt c¶ thuèc tõ hµnh trang vÒ r­¬ng nµy

[TipBtn]
Left=6
Top=6
Width=18
Height=18
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,255,255
Over=1
Image=\spr\vng\»î¶¯½éÉÜ°´Å¥.spr
Tip=<color=green>Ctrl+Chuét Ph¶i<color><enter>®Ó chuyÓn vËt phÈm ra khái r­¬ng më réng

