[Main]
Left=0
Top=0
Width=222
Height=200
Image=\spr\ui_hh\All_Box\box_getmoney.spr
Moveable=0

[MoneyInput]
Left=20
Top=52
Width=200
Height=14
Font=14
HAlign=1
Type=0
MultiLine=0
MaxLen=16
Color=255,253,122
BorderColor=255,0,0

[MoneyText]
Left=20
Top=75
Width=200
Height=14
Font=12
HAlign=0
Color=200,200,200
Text=0 vπn

[Title]
Left=15
Top=8
Width=210
Height=14
Font=14
HAlign=1
Color=255,217,78
Text=Title
DummyWnd=1

[OkBtn]
Left=50
Top=105
Width=75
Height=24
HAlign=1
VAlign=1
LabelYOffset=4
Font=12
Color=255,255,255
Over=1
Image=\spr\ui_hh\All_Box\btn_xacnhan.spr
;Label=X∏c nhÀn
Tip=Ph›m tæt: <color=green>Enter<color>

[CancelBtn]
Left=135
Top=105
Width=75
Height=24
HAlign=1
VAlign=1
LabelYOffset=4
Font=12
Color=255,255,255
Over=1
Image=\spr\ui_hh\All_Box\btn_huybo.spr
;Label=HÒy
Tip=Ph›m tæt: <color=green>ESC<color>
