[Main]
Left=562
Top=20
Width=223
Height=491
Moveable=1
StartPos=800,100
Trans=1
Image=\Spr\Ui3\UiItem\main.spr

[TitleIcon]
Left=6
Top=32
Width=65
Height=28
;Image=\Spr\Ui3\????\name.spr

[Title]
Left=74
Top=7
Width=258
Height=17
Font=16
HAlign=0
VAlign=0
Color=255,253,122
Text=Hµnh Trang
DummyWnd=1
;BorderColor=255,0,0

[CloseBtn]
Left=200
Top=5
Width=24
Height=24
Up=0
Down=1
Over=2
OverFrame=2
Image=\Spr\Ui3\UiItem\close.spr
Tip=

[GetMoneyBtn]
Left=10
Top=431
Width=67
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,235,214
Over=1
Image=\spr\ui3\UiItem\btn_guitien.spr
; Label=Gˆi Ti“n
Tip=Gˆi ti“n

[Money]
Left=43
Top=386
Width=100
Height=14
HAlign=0
VAlign=1
Text=Ti“n
Font=14
Color=255,217,78
Tip=<color=yellow>Ti“n vπn<color>

;[MoneyIcon]
;Left=25
;Top=350
;Width=110
;Height=14
;Font=14
;HAlign=1
;Color=255,217,78
;Image=\spr\ui3\????\yingliangtubiao.spr

[Gold]
Left=160
Top=386
Width=100
Height=14
HAlign=0
VAlign=1
Font=14
Color=255,0,0
Text=123
Tip=<color=green>Ti“n xu<color>

;[GoldIcon]
;Left=26
;Top=367
;Width=12
;Height=12
;Font=14
;HAlign=1
;Color=255,17,78
;Image=\spr\item\tongqian.spr

;[OpenStatus]
;Left=70
;Top=414
;Width=72
;Height=28
;Up=0
;Down=1
;Over=2
;OverFrame=2
;Image=\spr\Ui3\????\??????????.spr

[ItemBox]
Left=10
Top=32
Width=203
Height=348
HUnits=7
VUnits=12
UnitBorder=2

[MakeAdvBtn]
Left=147
Top=408
Width=67
Height=19
Up=0
Down=1
Over=2
OverFrame=2
Image=\spr\ui3\UiItem\btn_loirao.spr

[MarkPriceBtn]
Left=78
Top=408
Width=67
Height=19
Up=0
Down=1
Over=2
OverFrame=2
Image=\spr\ui3\UiItem\btn_dinhgia.spr

[MakeStallBtn]
Left=147
Top=408
Width=67
Height=19
Up=0
Down=2
Over=2
OverFrame=2
CheckBox=2
CheckOver=2
Image=\spr\ui3\UiItem\btn_raoban.spr

[Settings]
BGBorderColor=100,80,30
BGSpriteColor=243,194,70
BGPurpleColor=188,40,255
BGPurpleBorder=100,80,123
BGPlatinaBorder=110,110,110
BGPlatinaColor=240,240,240

[TipBtn]
Left=8
Top=6
Width=18
Height=18
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,255,255
Over=1
Image=\spr\vng\ªÓ∂ØΩÈ…‹∞¥≈•.spr
Tip=<color=green>Ctrl+ChuÈt Ph∂i<color><enter>?? chuy”n vÀt ph»m vµo r?¨ng m? rÈng<enter><enter><color=green>ChuÈt Ph∂i<color><enter>?? chuy”n vÀt ph»m vµo r?¨ng ch¯a ??

[XepDoBtn]
Left=10
Top=408
Width=67
Height=19
Up=0
Down=1
Over=2
OverFrame=2
Image=\spr\ui3\UiItem\btn_xepdo.spr
Tip=Sap xep hanh trang

[HuyVatPham]
Left=113
Top=459
Width=101
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=0,255,0
Over=1
; Label=HÒy VÀt Ph»m
Image=\spr\ui3\UiItem\btn_huyvatpham.spr

[RuongVoHan]
Left=10
Top=459
Width=101
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=0,255,0
Over=1
; Label=R?¨ng V? Hπn
Image=\spr\ui3\UiItem\btn_ruongvohan.spr
Tip=Ph›m tæt: <color=green>F11<color>

[OpenBoxBtn]
Left=78
Top=431
Width=67
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,235,214
Over=1
Image=\spr\ui3\UiItem\btn_moruong.spr
; Label=M? R?¨ng
Tip=Ph›m tæt: <color=green>Ctrl+Z<color>

[OpenShopBtn]
Left=147
Top=431
Width=67
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,235,214
Over=1
; Label=M? Shop
Image=\spr\ui3\UiItem\btn_moshop.spr
Tip=Ph›m tæt: <color=green>Ctrl+G<color>