; --------------------------------------------------------

; 功能 看对方玩家装备窗口
; --------------------------------------------------------
;男背景
[Male]
Left=297
Top=80
Width=205
Height=450
Moveable=1
Trans=0
Image=\spr\ui_hh\UiParadeItem\tintucnam.spr

;女背景
[Female]
Left=297
Top=80
Width=205
Height=450
Moveable=1
Trans=0
Image=\spr\ui_hh\UiParadeItem\tintucnu.spr

;帽子

[Face]
Left=128
Top=42
Width=70
Height=70

[FactionIcon]
Left=5
Top=3
Width=24
Height=24

[AvatarMale]
Left=128
Top=42
Width=1
Height=1
Image=\Spr\Ui3\UiChooseFace\Nam8.spr

[AvatarFemale]
Left=128
Top=42
Width=1
Height=1
Image=\Spr\Ui3\UiChooseFace\Nu3.spr

[Cap]
Left=70
Top=116
Width=50
Height=50
HaveBgColor=0

[Hoods]
Left=-50
Top=291
Width=50
Height=50
HaveBgColor=0

;武器
[Weapon]
Left=152
Top=185
Width=50
Height=102
HaveBgColor=0

;脖子戴的
[Necklace]
Left=152
Top=154
Width=50
Height=24
HaveBgColor=0

;手镯
[Bangle]
Left=15
Top=160
Width=24
Height=50
HaveBgColor=0

;衣服
[Cloth]
Left=70
Top=177
Width=50
Height=76
HaveBgColor=0

[Cloak]
Left=-51
Top=359
Width=50
Height=76
HaveBgColor=0
;腰带
[Sash]
Left=70
Top=264
Width=50
Height=24
HaveBgColor=0

;戒指1
[Ring1]
Left=15
Top=218
Width=24
Height=24
HaveBgColor=0

;戒指2
[Ring2]
Left=15
Top=248
Width=24
Height=24
HaveBgColor=0

;饰缀
[Pendant]
Left=15
Top=282
Width=24
Height=50
HaveBgColor=0

;鞋
[Shoes]
Left=152
Top=294
Width=50
Height=50
HaveBgColor=0

;马
[Horse]
Left=73
Top=304
Width=50
Height=76
HaveBgColor=0

[Mask]
Left=15
Top=132
Width=24
Height=24
HaveBgColor=0


;[EquipExpandBtn]
;Left=34
;Top=342
;Width=34
;Height=34
;Up=1
;Down=0
;CheckBox=1
;Trans=0
;Image=\Spr\Ui3\系统选项\Mask-Open.spr

;[EquipExpandImg]
;Left=-52
;Top=289
;Width=142
;Height=148
;Up=1
;Down=0
;CheckBox=1
;Trans=0
;Image=\Spr\Ui3\系统选项\EquipExpandImg.spr

;phi phong
[Mantle]
Left=15
Top=350
Width=27
Height=27
HaveBgColor=0

;an'
[Signet]
Left=152
Top=350
Width=27
Height=27
HaveBgColor=0

;trang suc
[Shipin]
Left=183
Top=350
Width=27
Height=27
HaveBgColor=0
;姓名
[Name]
Left=12
Top=47
Width=112
Height=14
Font=14
HAlign=1
Color=0,255,0

;帮派
[Tong]
Left=12
Top=80
Width=112
Height=14
Font=14
HAlign=1
Color=0,255,0

;帮派
[Rank]
Left=7
Top=55
Width=112
Height=14
Font=14
HAlign=1
Color=255,217,78

;称号
[Title]
Left=12
Top=64
Width=112
Height=14
Font=14
HAlign=1
Color=255,217,78

;绰号
[Agname]
Left=7
Top=90
Width=112
Height=14
Font=14
HAlign=1
Color=255,217,78

[Close]
Left=189
Top=3
Width=24
Height=24
LabelYOffset=4
Over=1
Image=\spr\ui_hh\UiItem\close.spr

[PKValue]
Left=35
Top=114
Width=30
Height=14
Font=14
HAlign=1
Color=0,255,0

;世界排名
[WorldRank]
Left=170
Top=115
Width=40
Height=12
Font=14
HAlign=1
Color=0,255,0

;声望值
[FuYuan]
Left=168
Top=121
Width=30
Height=12
Font=12
HAlign=1
Color=0,255,0

[Prestige]
Left=170
Top=135
Width=40
Height=12
Font=12
HAlign=1
Color=0,255,0

[TransLife]
Left=12
Top=45
Width=112
Height=14
Font=14
HAlign=1
Color=0,255,0

;配偶名字
[MateName]
Left=90
Top=392
Width=110
Height=14
Font=14
HAlign=1
Color=255,217,78

;界面设置值
[Settings]
BGBorderColor=100,80,30
BGSpriteColor=243,194,70
BGPurpleColor=188,40,255
BGPurpleBorder=100,80,123
BGPlatinaBorder=110,110,110
BGPlatinaColor=240,240,240
