[Main]
Left=75
Top=75
Width=650
Height=450
Moveable=1
Image=\spr\Ui3\pet\pet_main.spr
ScriptFile=\script\petsys\ui.lua

[CloseBtn]
Left=247
Top=427
Width=155
Height=20
CheckBox=0
Image=\spr\Ui3\pet\close.spr
Up=0
Down=1
Over=2

;==============================================================================

[TameBtn]
Left=336
Top=243;253
Width=120
Height=20
Image=\spr\Ui3\pet\btn.spr
Up=0
Down=1
Over=2
Color=255,255,255
OverColor=124,255,125
DisableColor=150,150,150
Font=14
LabelYOffset=4
Label=Tu luyện

;????
[SummonBtn]
Left=466
Top=243;253
Width=120
Height=20
Image=\spr\Ui3\pet\btn.spr
Up=0
Down=1
Over=2
Font=14
LabelYOffset=4
Color=255,255,255
OverColor=124,255,125
DisableColor=150,150,150
Label=Gọi Hảo Hữu

;????
[ChangeNameBtn]
Left=336
Top=263;283
Width=120
Height=20
Image=\spr\Ui3\pet\btn.spr
Up=0
Down=1
Over=2
Font=14
LabelYOffset=4
Color=255,255,255
OverColor=124,255,125
DisableColor=150,150,150
Label=Đổi tên

;????
[UnSummonBtn]
Left=466
Top=263;283
Width=120
Height=20
Image=\spr\Ui3\pet\btn.spr
Up=0
Down=1
Over=2
Font=14
LabelYOffset=4
Color=255,255,255
OverColor=124,255,125
DisableColor=150,150,150
Label=Thu hồi

;????
[ChangeFeatureBtn]
Left=336
Top=283;313
Width=120
Height=20
Image=\spr\Ui3\pet\btn.spr
Up=0
Down=1
Over=2
Font=14
LabelYOffset=4
Color=255,255,255
OverColor=124,255,125
DisableColor=150,150,150
Label=Đổi ngoại quan

;????
[DeleteBtn]
Left=466
Top=283;313
Width=120
Height=20
Image=\spr\Ui3\pet\btn.spr
Up=0
Down=1
Over=2
Font=14
LabelYOffset=4
Color=255,255,255
OverColor=124,255,125
DisableColor=150,150,150
Label=Xóa Hảo Hữu

;????
[LevelUpBtn]
Left=336
Top=303;343
Width=120
Height=20
Image=\spr\Ui3\pet\btn.spr
Up=0
Down=1
Over=2
Font=14
LabelYOffset=4
Color=255,255,255
OverColor=124,255,125
DisableColor=150,150,150
Label=Thăng cấp


[EggBtn]
Left=466
Top=303;343
Width=120
Height=20
Image=\spr\Ui3\pet\btn.spr
Up=0
Down=1
Over=2
Font=14
LabelYOffset=4
Color=255,255,255
OverColor=124,255,125
DisableColor=150,150,150
Label=Chuyển thành trứng

[AutoPickItemCK]
Left=336
Top=323;380
Width=14
Height=14
Up=0
Down=1
CheckBox=1
DisableFrame=2
Trans=0
Image=\spr\Ui3\UiAutoPlay\CheckBox.spr

[AutoPickItemTxt]
Left=354
Top=323;379
Width=96
Height=16
Font=14
Color=255,255,255
Text=Nhặt đồ

[AutoPickMoneyCK]
Left=466
Top=323;380
Width=14
Height=14
Up=0
Down=1
CheckBox=1
DisableFrame=2
Trans=0
Image=\spr\Ui3\UiAutoPlay\CheckBox.spr

[AutoPickMoneyTxt]
Left=484
Top=323;379
Width=100
Height=16
Font=14
Color=255,255,255
Text=Nhặt tiền

[PatrolCK]
Left=336
Top=342;403
Width=14
Height=14
Up=0
Down=1
CheckBox=1
DisableFrame=2
Trans=0
Image=\spr\Ui3\UiAutoPlay\CheckBox.spr

[PatrolTxt]
Left=354
Top=342;402
Width=96
Height=16
Font=14
Color=255,255,255
Text=Tuần tra

[IdleChatCK]
Left=466
Top=342;403
Width=14
Height=14
Up=0
Down=1
CheckBox=1
DisableFrame=2
Trans=0
Image=\spr\Ui3\UiAutoPlay\CheckBox.spr

[IdleChatTxt]
Left=484
Top=342;402
Width=100
Height=16
Font=14
Color=255,255,255
Text=Chat nhóm

[ShowSeriesCK]
Left=336
Top=361;423
Width=14
Height=14
Up=0
Down=1
CheckBox=1
DisableFrame=2
Trans=0
Image=\spr\Ui3\UiAutoPlay\CheckBox.spr

[ShowSeriesTxt]
Left=354
Top=361;422
Width=130
Height=16
Font=14
Color=255,255,255
Text=Icon ngũ hành

[AppearanceImg]
Left=39
Top=276
Width=230
Height=170

;==============================================================================
[UpgradeTxt]
Left=55
Top=86
Font=14
Color=255,255,255
Text=Điểm thăng cấp

[GrownTxt]
Left=55
Top=106
Font=14
Color=255,255,255
Text=Điểm tăng trưởng:

[TameTxt]
Left=55
Top=126
Font=14
Color=255,255,255
Text=Điểm tu luyện:

[NameTxt]
Left=55
Top=158
Font=14
Color=255,255,255
Text=Tên

[LevelTxt]
Left=55
Top=178
Font=14
Color=255,255,255
Text=Đẳng cấp

[StrTxt]
Left=55
Top=198
Font=14
Color=255,255,255
Text=Sức mạnh:

[DexTxt]
Left=180
Top=198
Font=14
Color=255,255,255
Text=Thân pháp:

[VitTxt]
Left=55
Top=218
Font=14
Color=255,255,255
Text=Ngoại công:

[EngTxt]
Left=180
Top=218
Font=14
Color=255,255,255
Text=Nội công:

[LifeTxt]
Left=55
Top=238
Font=14
Color=255,255,255
Text=Sinh lực:

[ManaTxt]
Left=180
Top=238
Font=14
Color=255,255,255
Text=Nội lực:

;==============================================================================
[UpgradeValueTxt]
Left=192
Top=86
Width=80
Height=20
Font=14
Color=255,255,255
;Text=????:

[GrownValueTxt]
Left=192
Top=106
Width=80
Height=20
Font=14
Color=255,255,255
;Text=????:

[TameValueTxt]
Left=192
Top=126
Width=80
Height=20
Font=14
Color=255,255,255
;Text=????:

[NameValueTxt]
Left=162
Top=158
Font=14
Color=255,255,255
;Text=??????:

[LevelValueTxt]
Left=162
Top=178
Font=14
Color=255,255,255
;Text=??????:

[StrValueTxt]
Left=135
Top=198
Font=14
Color=255,255,255
;Text=??:

[DexValueTxt]
Left=257
Top=198
Font=14
Color=255,255,255
;Text=??:

[VitValueTxt]
Left=135
Top=218
Font=14
Color=255,255,255
;Text=??:

[EngValueTxt]
Left=257
Top=218
Font=14
Color=255,255,255
;Text=??:

[LifeValueTxt]
Left=135
Top=238
Font=14
Color=255,255,255
;Text=??:

[ManaValueTxt]
Left=257
Top=238
Font=14
Color=255,255,255
;Text=??:

;==============================================================================
[Skill_1]
Left=368
Top=159
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

[Skill_2]
Left=420
Top=159
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

[Skill_3]
Left=471
Top=159
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

[Skill_4]
Left=523
Top=159
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

[Skill_5]
Left=575
Top=159
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

;==============================================================================

;==============================================================================
; Pet equip slots: weapon, helm, armor, boots, ring, pendant, amulet
[Equip_1]
Left=334
Top=74
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

;mu
[Equip_2]
Left=374
Top=74
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

;ao
[Equip_3]
Left=414
Top=74
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

;giay
[Equip_4]
Left=454
Top=74
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

;nhan
[Equip_5]
Left=494
Top=74
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

;day chuyen
[Equip_6]
Left=534
Top=74
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

[Equip_7]
Left=574
Top=74
Width=40
Height=40
Trans=1
Image=\spr\Ui4\uipet\ui\Propbox.spr
HaveBgColor=0

;==============================================================================
