[Main]
Left=40
Top=40
Width=260
Height=500
Moveable=1
StartPos=-211,100
Trans=1
Image=\spr\ui_hh\UiShop\main.spr

[TextName]
Left=0
Top=7
Width=215
Height=24
Font=16
HAlign=1
VAlign=0
Color=255,253,122
Text=Hµnh Trang MÎ RÈng
;BorderColor=255,0,0
DummyWnd=1


[CloseBtn]
Left=197
Top=3
Image=\spr\ui_hh\UiItem\close.spr
Font=12
Width=24
Height=24
Color=200,200,200
;Label=ß„ng (ESC)
Tip=Ph›m tæt: <color=green>ESC<color>
Up=0
Down=1
Over=2
OverFrame=2

[ItemBox]
Left=10
Top=32
Width=203
Height=348
HUnits=7
VUnits=12
UnitBorder=2
[Settings]
BGBorderColor=100,80,30
BGSpriteColor=243,194,70
BGPurpleColor=188,40,255
BGPurpleBorder=100,80,123
