[Main]
Left=506
Top=180
Width=210
Height=321
Image=\spr\vlcc\dialog\chienma.spr
;Trans=1
Moveable=1

[Title]
Left=18
Top=1
Width=200
Height=17
Font=12
HAlign=0
VAlign=2
Color=255,253,122
Text=Chi�n M�
DummyWnd=1
;BorderColor=255,0,0

[CloseBtn]
Left=188
Top=3
Width=20
Height=20
Over=1
Image=\spr\ui_hh\UiItem\close.spr
;Label=H�y
Tip=Ph�m t�t: <color=green>ESC<color>

[LayNgua]
Left=106
Top=293
Width=98
Height=20
HAlign=1
VAlign=1
LabelYOffset=3
Font=12
Color=169,211,190
OverColor=124,255,125
SelectColor=77,77,77
DisableColor=77,77,77
Up=0
Down=2
Over=2
Trans=0
Image=\spr\control\tab.spr
Label=L�y ng�a
Tip=L�y ng�a
NoOverSound=1

[NangCap]
Left=7
Top=293
Width=98
Height=20
HAlign=1
VAlign=1
LabelYOffset=3
Font=12
Color=169,211,190
OverColor=124,255,125
SelectColor=77,77,77
DisableColor=77,77,77
Up=0
Down=2
Over=2
Trans=0
Image=\spr\control\tab.spr
Label=��t Ph�
Tip=T�ng c�p �� chi�n m�
NoOverSound=1

[ObjectChienMa]
Left=22
Top=32
Width=52
Height=108

[TitleChienMa]
Left=100
Top=31
Width=85
Height=14
Font=12
HAlign=1
Color=255,217,78
Text=Lv.5 Chi�u D�

[ExpChienMa]
Left=75
Top=49
Width=130
Height=14
Font=12
HAlign=1
Color=255,217,78
Text=2117760/2117760

[ExpBar]
Left=88
Top=67
Width=130
Height=14
PartType=1

[ExpBar_Image]
Left=0
Top=0
Width=130
Height=14
Trans=0
Image=\spr\control\part_progress_bar.spr

[ExpBar_Text]
Left=0
Top=-2
Width=110
Height=14
Trans=0
Text=85%
Color=255,217,78
Font=12
HAlign=1
VAlign=1

[ExpBar_Bg]
Left=85
Top=65
Width=130
Height=14
Image=\spr\control\bg_progress_bar.spr

[ContentList]
Left=91
Top=82
Width=100
Height=84
Font=12
HAlign=0
VAlign=1
MsgLineCount=40,40
MaxMsgCount=40
MsgColor=255,217,78

[ContentScroll]
Left=190
Top=73
Width=7
Height=60
Type=1
Min=0
Max=9
PageSize=1
SlideBegin=3
SlideEnd=63

[ContentScroll_Btn]
Left=0
Top=0
Width=4
Height=10
Up=0
Down=0
Over=0
OverFrame=0
Trans=0
;Image=\spr\Ui3\�������\�α�.spr
NoOverSound=1


[LeftBtn]
Left=115
Top=132
Width=22
Height=21
Over=1
OverFrame=1
Image=\spr\ui_hh\UiStoreBox\btn_lui.spr
Tip=tr��c
NoOverSound=1

[RightBtn]
Left=141
Top=132
Width=22
Height=21
Over=1
OverFrame=1
Image=\spr\ui_hh\UiStoreBox\btn_toi.spr
Tip=k�
NoOverSound=1

