[Main]
Left=117
Top=109
Width=566
Height=383
Image=\Spr\Ui3\UiSelServer\main.spr
Moveable=0
DummyWnd=1
StartPos=800,0
LoginBg=Login
WCenter=1,1

; Region list - left column
[List]
Left=18
Top=42
Width=285
Height=280
Font=14
RowDis=3
Color=255,255,255
SelColor=255,253,122
SelBorderColor=255,0,0
SelItemBgColor=150,142,105
HAlign=1

; Server list for the selected Region - right column
[ServerList]
Left=343
Top=72
Width=200
Height=250
Font=14
RowDis=3
Color=255,255,255
SelColor=255,253,122
SelBorderColor=255,0,0
SelItemBgColor=150,142,105
HAlign=1

[Scroll]
Left=315
Top=48
Width=11
Height=275
Type=1
Min=0
Max=40
PageSize=1
SlideBegin=13
SlideEnd=287

[Scroll_Btn]
Left=0
Top=0
Width=11
Height=27
Up=0
Down=0
Over=0
OverFrame=0
Trans=0
Image=

[ServerScroll]
Left=550
Top=48
Width=11
Height=275
Type=1
Min=0
Max=40
PageSize=1
SlideBegin=13
SlideEnd=287

[ServerScroll_Btn]
Left=0
Top=0
Width=11
Height=27
Up=0
Down=0
Over=0
OverFrame=0
Trans=0
Image=

[Login]
Left=70
Top=335
Width=187
Height=29
Up=0
Down=1
Over=2
OverFrame=3
Trans=0
Image=\Spr\Ui3\UiSelServer\btn_xacnhan.spr

[Cancel]
Left=350
Top=335
Width=187
Height=29
Up=0
Down=1
Over=2
OverFrame=3
Trans=0
Image=\Spr\Ui3\UiSelServer\btn_huybo.spr
