[Main]
Left=0
Top=55
Width=223
Height=449
Moveable=1
StartPos=-214,100
Trans=1
Image=\spr\ui_hh\UiShop\main.spr

[Title]
Left=0
Top=7
Width=215
Height=24
Font=16
HAlign=1
VAlign=0
Color=255,253,122
Text=Cöa Hµng
;BorderColor=255,0,0
DummyWnd=1

[ItemBox]
Left=10
Top=32
Width=203
Height=348
HUnits=7
VUnits=12
UnitBorder=2
AcceptFree=1

[BuyBtn]
Left=8
Top=418
Width=67
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,255,255
Over=1
Image=\spr\ui_hh\UiShop\btn_mua.spr
; Label=Mua

[SellBtn]
Left=78
Top=418
Width=67
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,255,255
Over=1
Image=\spr\ui_hh\UiShop\btn_ban.spr
; Label=B¸n

[RepairBtn]
Left=148
Top=418
Width=67
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,255,255
Over=1
Image=\spr\ui_hh\UiShop\btn_sua.spr
; Label=Söa

[RepairBtnAll]
Left=8
Top=387
Width=101
Height=19
HAlign=1
VAlign=1
LabelYOffset=6
Font=12
Color=255,255,255
Over=1
Image=\spr\ui_hh\UiShop\btn_suatatca.spr
; Label=Söa tÊt c¶

[LeftBtn]
Left=165
Top=383
Width=22
Height=21
Over=1
DisableFrame=2
OverFrame=1
Image=\spr\ui_hh\UiStoreBox\btn_lui.spr
Tip=Trang tr­íc

[RightBtn]
Left=191
Top=383
Width=22
Height=21
Over=1
DisableFrame=2
OverFrame=1
Image=\spr\ui_hh\UiStoreBox\btn_toi.spr
Tip=Trang kÕ

[CloseBtn]
Left=197
Top=3
Width=24
Height=24
Over=1
Image=\spr\ui_hh\UiItem\close.spr
;Label=Hñy
Tip=PhÝm t¾t: <color=green>ESC<color>

[Settings]
BGBorderColor=100,80,30
BGSpriteColor=243,194,70
BGPurpleColor=188,40,255
BGPurpleBorder=100,80,123
