; ¼¼ÄÜ´°¿Ú - Õ½¶·¼¼ÄÜ

[Main]
Left=4
Top=80
Width=519
Height=282
Moveable=1
Trans=0
Image=\spr\Ui3\UiSkillNew\main.spr

[Title]
Left=0
Top=9
Width=519
Height=18
HAlign=1
VAlign=1
Color=255,255,255
BorderColor=0,0,0
Font=14
Text=Kỹ năng

[CloseBtn]
Left=493
Top=5
Width=19
Height=19
Up=0
Down=1
Over=2
OverFrame=2
Trans=0
Image=\spr\Ui3\UiSkillNew\close.spr

[FightBtn]
Left=8
Top=34
Width=100
Height=18
Up=1
Down=0
CheckBox=1
Trans=0
Image=\spr\Ui3\UiSkillNew\skilltype.spr
Label=Chủ động
Font=12
Color=255,253,122
BorderColor=0,0,0
SelectColor=255,255,255
SelectBorderColor=0,0,0

[LiveBtn]
Left=111
Top=34
Width=100
Height=18
Up=1
Down=0
CheckBox=1
Trans=0
Image=\spr\Ui3\UiSkillNew\skilltype.spr
Label=Thông dụng
Font=12
Color=255,253,122
BorderColor=0,0,0
SelectColor=255,255,255
SelectBorderColor=0,0,0

[SkillTypeBtn]
Left=8
Top=34
Width=76
Height=18
Up=1
Down=0
CheckBox=1
Trans=0
Image=\spr\Ui3\UiSkillNew\skilltype.spr
Label=SkillType
Font=12
Color=255,253,122
BorderColor=0,0,0
SelectColor=255,255,255
SelectBorderColor=0,0,0

[RemainPoint]
Left=460
Top=250
Width=40
Height=13
HAlign=1
Color=255,253,122
BorderColor=255,0,0
Font=12

[RemainPointTitle]
Left=270
Top=250
Width=180
Height=15
Font=12
Color=255,255,145
HAlign=2
Text=Điểm kỹ năng còn:

[ImgSplitLine]
Left=51
Top=1
Width=100
Height=14
Trans=1
Image=\spr\Ui3\UiSkillNew\line.spr

[ImgColTitle]
Left=2
Top=57
Width=48
Height=20
Trans=1
Image=\spr\Ui3\UiSkillNew\leveltext.spr

[ImgSkillBG]
Left=6
Top=28
Width=100
Height=14
Trans=1
Image=\spr\Ui3\UiSkillNew\skillicon.spr

[ImgCommonSkillBG]
Left=6
Top=12
Width=100
Height=14
Trans=1
Image=\spr\Ui3\UiSkillNew\skillicon.spr

[TxtColTitle]
Left=-1
Top=57
Width=55
Height=20
HAlign=1
VAlign=1
Color=255,253,122
BorderColor=0,0,0
Font=12

[Skill]
Left=8
Top=84
Width=36
Height=36
HaveBgColor=0

[CommonSkill]
Left=8
Top=84
Width=36
Height=36
HaveBgColor=0

[AddPointBtn]
Left=0
Top=0
Width=14
Height=14
Trans=0
Up=1
Down=0
DisableFrame=2
Image=\spr\Ui3\UiSkillNew\plus.spr
Tip=Tăng điểm kỹ năng

[AddCommonPointBtn]
Left=0
Top=0
Width=14
Height=14
Trans=0
Up=1
Down=0
DisableFrame=2
Image=\spr\Ui3\UiSkillNew\plus.spr
Tip=Tăng điểm kỹ năng

[SkillText]
Offset=0,36
Font=12
Color=218,255,165
BorderColor=23,68,0

[ColTitle]
Title_1=Thấp
Tip_1=Tuyệt Học-Thấp
Title_2=Cao
Tip_2=Tuyệt Học-Cao
Title_3=Nhập môn
Title_4=Lv10
Title_5=Lv20
Title_6=Lv30
Title_7=Lv40
Title_8=Lv50
Title_9=Trên Phái
Title_10=Lv60
Title_11=Lv120
Title_12=Lv150

