; --------------------------------------------------------
; ÎÄ¼þÃû£º
; ¹¦ÄÜ ÈËÎï×´Ì¬×°±¸´°¿Ú_¾­Âö×ÓÒ³
; --------------------------------------------------------

[Main]
Left=4
Top=49
Width=314
Height=356
Moveable=0
Trans=0
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµ×.spr

[txtCurZYCount]
Left=0
Top=350
Width=300
Height=20
HAlign=1
VAlign=1
Font=14
Color=169,211,190
SelectColor=77,77,77

[txtCurXYCount]
Left=0
Top=370
Width=300
Height=20
HAlign=1
VAlign=1
Font=14
Color=169,211,190
SelectColor=77,77,77

[MeridianConfig]
Left=5
Top=44
Width=67
Height=19
Up=0
Down=0
Trans=0
Font=14
LabelYOffset=3
Color=255,255,255
OverColor=124,255,125
SelectColor=225,213,43
Image=\Spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr

[BtnFullBreath]
Left=5
Top=20
Width=67
Height=19
Up=0
Down=0
Trans=0
Font=14
LabelYOffset=3
Color=255,255,255
OverColor=124,255,125
SelectColor=225,213,43
Label=KhÝ Doanh §an §iÒn
Image=\Spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr
[imgBreathPoint_0]
Left=149
Top=76
Width=10
Height=11
Tip=§èc M¹ch
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã.spr
[imgBreathPoint_1]
Left=189
Top=76
Width=10
Height=11
Tip=Nh©m M¹ch
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã.spr
[imgBreathPoint_2]
Left=217
Top=104
Width=10
Height=11
Tip=Xung M¹ch
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã.spr
[imgBreathPoint_3]
Left=217
Top=144
Width=10
Height=11
Tip=§íi M¹ch
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã.spr
[imgBreathPoint_4]
Left=189
Top=172
Width=10
Height=11
Tip=¢m Duy M¹ch
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã.spr
[imgBreathPoint_5]
Left=149
Top=172
Width=10
Height=11
Tip=D­¬ng Duy M¹ch
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã.spr
[imgBreathPoint_6]
Left=121
Top=144
Width=10
Height=11
Tip=¢m Khiªu M¹ch
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã.spr
[imgBreathPoint_7]
Left=121
Top=104
Width=10
Height=11
Tip=D­¬ng Khiªu M¹ch
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã.spr

[imgBreathPoint2_0]
Left=149
Top=76
Width=10
Height=11
Tip=§èc M¹ch<enter>Ngò Hµnh C­êng hãa %: T¨ng
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã¸ß¼¶.spr
[imgBreathPoint2_1]
Left=189
Top=76
Width=10
Height=11
Tip=Nh©m M¹ch<enter>Ngò Hµnh Nh­îc hãa %: Gi¶m
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã¸ß¼¶.spr
[imgBreathPoint2_2]
Left=217
Top=104
Width=10
Height=11
Tip=Xung M¹ch<enter>Sinh Lùc tèi ®a (D­¬ng) : T¨ng
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã¸ß¼¶.spr
[imgBreathPoint2_3]
Left=217
Top=144
Width=10
Height=11
Tip=§íi M¹ch<enter>Phßng Thñ VËt Lý (D­¬ng) %: T¨ng
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã¸ß¼¶.spr
[imgBreathPoint2_4]
Left=189
Top=172
Width=10
Height=11
Tip=¢m Duy M¹ch<enter> Kh¸ng B¨ng (D­¬ng) %: T¨ng
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã¸ß¼¶.spr
[imgBreathPoint2_5]
Left=149
Top=172
Width=10
Height=11
Tip=D­¬ng Duy M¹ch<enter>Kh¸ng Háa (D­¬ng) %: T¨ng
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã¸ß¼¶.spr
[imgBreathPoint2_6]
Left=121
Top=144
Width=10
Height=11
Tip=¢m Khiªu M¹ch<enter>Kh¸ng L«i (D­¬ng) %: T¨ng
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã¸ß¼¶.spr
[imgBreathPoint2_7]
Left=121
Top=104
Width=10
Height=11
Tip=D­¬ng Khiªu M¹ch<enter>Kh¸ng §éc (D­¬ng) %: T¨ng
Image=\Spr\Ui4\Ö÷½çÃæ\¾­ÂöÏµÍ³\¾­Âöµã¸ß¼¶.spr

[Btn1DayBreath]
Left=220
Top=217
Width=67
Height=19
Up=0
Down=2
Trans=1
DisableFrame=3
Font=14
LabelYOffset=3
Color=255,255,255
OverColor=124,255,125
SelectColor=225,213,43
Tip=Khi Doanh §an §iÒn thªm 1 ngµy
Label=1 ngµy
Image=\Spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr

[Btn7DaysBreath]
Left=220
Top=241
Width=67
Height=19
Up=0
Down=2
Trans=1
DisableFrame=3
Font=14
LabelYOffset=3
Color=255,255,255
OverColor=124,255,125
SelectColor=225,213,43
Tip=KhÝ Doanh §an §iÒn liªn tôc 3 ngµy
Label=3 ngµy
Image=\Spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr

[Btn30DaysBreath]
Left=220
Top=265
Width=67
Height=19
Up=0
Down=2
Trans=1
DisableFrame=3
Font=14
LabelYOffset=3
Color=255,255,255
OverColor=124,255,125
SelectColor=225,213,43
Tip=Khi Doanh §an §iÒn thªm 7 ngµy
Label=7 ngµy
Image=\Spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr

[BtnViewMoreBuff]
Left=220
Top=289
Width=67
Height=19
Up=0
Down=2
Trans=1
DisableFrame=3
Font=14
LabelYOffset=3
Color=255,255,255
OverColor=124,255,125
SelectColor=225,213,43
Tip=Xem thuéc tÝnh t¨ng cÊp kinh m¹ch
Label=Xem tÊt c¶ thuéc tÝnh
Image=\Spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr

[BreathCosts]
Count=3
0_Day=1
0_Pill=200
1_Day=3
1_Pill=400
2_Day=7
2_Pill=600
AttributeAdd=15
AttributeMinus=15
AttributeQuankang=5

[EffectTarget]
0_Target=Méc
1_Target=Thæ 
2_Target=Háa
3_Target=Kim
4_Target=Thñy 

[BreathBuffInfo]
Left=82
Top=220
Width=140
Height=15
Font=12
BorderColor=0,0,0
MultiLine=1
Color=255,255,255
Text=
