; --------------------------------------------------------
; ÎÄ¼þÃû£º
; ¹¦ÄÜ ÈËÎï×´Ì¬×°±¸´°¿Ú_³ÆºÅ¹ÜÀí
; --------------------------------------------------------

[Main]
Left=4
Top=49
Moveable=0
Trans=0
Image=\spr\Ui4\Ö÷½çÃæ\½ÇÉ«ÐÅÏ¢×ÊÔ´\½­ºþÆÀ¼Û.spr


;µ±Ç°ÕýÔÚÊ¹ÓÃµÄ³ÆºÅ
[UsedTitle]
Left=4
Top=15
Width=286
Height=30
Font=12
HAlign=1
WAlign=1
Color=255,217,78


;³ÆºÅÁÐ±íÅäÖÃ
[TitleList]
Left=7
Top=53
Width=120
Height=245
Font=12
MaxMsgCount=90
MsgColor=218,255,165
Selable=1
SelBgColor=110,110,90
SelBgColorAlpha=100
SelColor=240,127,80
RowInterval=4
;BKColor=34,34,34

;³ÆºÅÁÐ±í¹ö¶¯Ìõ
[TitleListScroll]
Left=135
Top=53
Width=14
Height=265
Type=1
Min=0
Max=9
PageSize=1
SlideBegin=20
SlideEnd=220

;
[TitleListScroll_Btn]
Left=0
Top=0
Width=14
Height=37
Up=0
Down=0
Over=0
OverFrame=0
Trans=0
Image=\spr\Ui4\common\ÍÏ¶¯Ìõ.spr


;³ÆºÅÏ¸½ÚÐÅÏ¢
[TitleDetail]
Left=154
Top=53
Width=120
Height=245
Font=12
MaxMsgCount=20
MsgColor=169,211,190
Selable=1
SelColor=169,211,190
RowInterval=4
;BKColor=34,34,34

[TitleDetailScroll]
Left=279
Top=53
Width=14
Height=265
Type=1
Min=0
Max=9
PageSize=1
SlideBegin=20
SlideEnd=220

[TitleDetailScroll_Btn]
Left=0
Top=0
Width=14
Height=37
Up=0
Down=0
Over=0
OverFrame=0
Trans=0
Image=\spr\Ui4\common\ÍÏ¶¯Ìõ.spr


;°ï»á
[Tong]
Left=50
Top=335
Length=50
Height=15
Font=12
HAlign=1
WAlign=1
Color=255,217,78
;BKColor=0,0,0


;°ï»áÖ°Îñ
[TongDuty]
Left=100
Top=355
Length=50
Height=15
Font=12
;HAlign=1
;WAlign=1
Color=255,217,78
;BKColor=34,34,34

;PKÖµ
[PKValue]
Left=220
Top=335
Length=80
Height=15
Font=12
HAlign=1
WAlign=1
Color=255,217,78
;BKColor=34,34,34

;×ªÉú
[TransLifeCount]
Left=250
Top=355
Length=80
Height=15
Font=12
HAlign=1
WAlign=1
Color=255,217,78
;BKColor=34,34,34


[TxtCurrentMessage_0]
Left=10
Top=335
Width=100
Height=15
Font=12
;HAlign=1
;WAlign=1
Color=255,255,255
MultiLine=0
Text=Bang: 



[TxtCurrentMessage_1]
Left=10
Top=355
Width=100
Height=15
Font=12
;HAlign=1
Color=255,255,255
MultiLine=0
Text=Chøc vô bang: 


[TxtCurrentMessage_2]
Left=170
Top=335
Width=100
Height=15
Font=12
;HAlign=1
Color=255,255,255
MultiLine=0
Text=TrÞ PK:



[TxtCurrentMessage_3]
Left=170
Top=355
Width=100
Height=15
Font=12
;HAlign=1
Color=255,255,255
MultiLine=0
Text=ChuyÓn sinh: 


[BkgImg1]
Left=2
Top=12
Moveable=0
Trans=0
Image=\spr\Ui4\Ö÷½çÃæ\½ÇÉ«ÐÅÏ¢×ÊÔ´\µ±Ç°³ÆºÅ¿ò.spr

[BkgImg2]
Left=2
Top=40
Moveable=0
Trans=0
Image=\spr\Ui4\Ö÷½çÃæ\½ÇÉ«ÐÅÏ¢×ÊÔ´\³ÆºÅ½çÃæ·ÖÀ¸.spr


[BkgImg3]
Left=2
Top=315
Moveable=0
Trans=0
Image=\spr\Ui4\Ö÷½çÃæ\½ÇÉ«ÐÅÏ¢×ÊÔ´\°ï»áµÈÐÅÏ¢·ÖÒ³.spr
