; --------------------------------------------------------
; ÎÄ¼þÃû£º
; ¹¦ÄÜ ÈËÎï×´Ì¬×°±¸´°¿Ú_Íæ¼ÒÊôÐÔ×ÓÒ³
; --------------------------------------------------------

[Main]
Left=4
Top=49
Width=294
Height=394
Moveable=0
Trans=0
;Image=\spr\Ui4\Ö÷½çÃæ\½ÇÉ«ÐÅÏ¢×ÊÔ´\ÊôÐÔµ×.spr
;ÆÀ¼Û»òÐÄÇé·¢±íµÄÊ±¼äÔÚµ±Ç°Ê±¼äÖ®ºó£¬³öAssert
AssertJudgeTimeError=0
BKColor=17,17,17

;Í·Ïñ
[Face]
Left=5
Top=7
Width=74
Height=74
StrokeColor=34,34,34

;µã»÷ÕâÀïÑ¡ÔñÍ·Ïñ
[ClickHere]
Left=7
Top=9
Width=70
Height=70
Font=12
HAlign=1
VAlign=1
MultiLine=1
Color=255,0,0
Text=NhÊp vµo ®©y ®Ó chän hinh d¸ng
StrokeColor=34,34,34

; ÈËÎï×´Ì¬²¿·Ö
;ÐÕÃû
[Name]
Left=145
Top=12
Width=143
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;³ÆºÅ
[Title]
Left=145
Top=28
Width=143
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;¸£ÔµÖµ
[Luck]
Left=145
Top=45
Width=45
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;µÈ¼¶
[Level]
Left=145
Top=62
Width=45
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÉùÍûÖµ
[Prestige]
Left=248
Top=45
Width=40
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÊÀ½çÅÅÃû
[WorldRank]
Left=248
Top=62
Width=40
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

[DividingLine_0]
Left=1
Top=83
Length=292
Color=34,34,34

Width=0
Height=0
[DividingLine_1]
Left=1
Top=156
Length=292
Color=34,34,34

Width=0
Height=0
[DividingLine_2]
Left=1
Top=228
Length=292
Color=34,34,34

Width=0
Height=0
[DividingLine_3]
Left=1
Top=283
Length=292
Color=34,34,34

Width=0
Height=0
[DividingLine_4]
Left=1
Top=370
Length=292
Color=34,34,34
;ÉúÃüÌõ
Width=0
Height=0
[Life]
Left=70
Top=161
Width=79
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÄÚÁ¦Ìõ
[Mana]
Left=70
Top=177
Width=79
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÌåÁ¦ÖµÌõ
[Stamina]
Left=70
Top=193
Width=79
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÊôÐÔ
[Status]
Left=70
Top=209
Width=79
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;Á¦Á¿
[Strength]
Left=216
Top=161
Width=59
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;Íâ¹¦
[Vitality]
Left=216
Top=177
Width=59
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;Éí·¨
[Dexterity]
Left=216
Top=193
Width=59
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÄÚ¹¦
[Energy]
Left=216
Top=209
Width=59
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;Ôö¼ÓÁ¦Á¿
[AddStrength]
Left=273
Top=161
Width=14
Height=14
Trans=0
Up=1
Down=2
DisableFrame=3
Image=\spr\Ui4\common\¼Óµã°´Å¥.spr

;Ôö¼ÓÍâ¹¦
[AddVitality]
Left=273
Top=177
Width=14
Height=14
Trans=0
Up=1
Down=2
DisableFrame=3
Image=\spr\Ui4\common\¼Óµã°´Å¥.spr

;Ôö¼ÓÉí·¨
[AddDexterity]
Left=273
Top=193
Width=14
Height=14
Trans=0
Up=1
Down=2
DisableFrame=3
Image=\spr\Ui4\common\¼Óµã°´Å¥.spr

;Ôö¼ÓÄÚ¹¦
[AddEnergy]
Left=273
Top=209
Width=14
Height=14
Trans=0
Up=1
Down=2
DisableFrame=3
Image=\spr\Ui4\common\¼Óµã°´Å¥.spr

;¾­ÑéÖµÌõ
[Exp]
Left=81
Top=233
Width=209
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;×óÉ±ÉËÁ¦
[LeftDamage]
Left=81
Top=249
Width=209
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÓÒÉ±ÉËÁ¦
[RightDamage]
Left=81
Top=265
Width=209
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÃüÖÐ
[Attack]
Left=70
Top=287
Width=83
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÉÁ±Ü
[Defense]
Left=70
Top=304
Width=83
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÅÜËÙ
[MoveSpeed]
Left=70
Top=320
Width=83
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;¹¥ËÙ
[AttackSpeed]
Left=70
Top=336
Width=83
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;Ê£ÓàµãÊý£¨Ç±ÄÜ£©
[RemainPoint]
Left=70
Top=352
Width=83
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;ÆÕ·À
[ResistPhy]
Left=219
Top=287
Width=72
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;±ù·À
[ResistCold]
Left=219
Top=304
Width=72
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;À×·À
[ResistLighting]
Left=219
Top=320
Width=72
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;»ð·À
[ResistFire]
Left=219
Top=336
Width=72
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

;¶¾·À
[ResistPoison]
Left=219
Top=352
Width=72
Height=15
Font=12
HAlign=1
Color=255,217,78
BKColor=34,34,34

[TextTitle_0]
Left=84
Top=12
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Danh TÝnh

[TextTitle_1]
Left=84
Top=29
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=X­ng hiÖu

[TextTitle_2]
Left=84
Top=46
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Phóc Duyªn

[TextTitle_3]
Left=84
Top=63
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=§¼ng cÊp

[TextTitle_4]
Left=193
Top=46
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Danh Väng

[TextTitle_5]
Left=193
Top=63
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=XÕp H¹ng

[TextTitle_6]
Left=10
Top=161
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Sinh Lùc

[TextTitle_7]
Left=10
Top=178
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Néi Lùc

[TextTitle_8]
Left=10
Top=194
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=ThÓ Lùc

[TextTitle_9]
Left=10
Top=210
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Thuéc TÝnh

[TextTitle_10]
Left=154
Top=161
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Søc M¹nh

[TextTitle_11]
Left=154
Top=178
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Sinh KhÝ

[TextTitle_12]
Left=154
Top=194
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Th©n Ph¸p

[TextTitle_13]
Left=154
Top=210
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Néi C«ng

[TextTitle_14]
Left=10
Top=232
Width=80
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Kinh NghiÖm

[TextTitle_15]
Left=10
Top=249
Width=80
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Lùc Tay Tr¸i

[TextTitle_16]
Left=10
Top=266
Width=80
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Lùc Tay Ph¶i

[TextTitle_17]
Left=10
Top=287
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=ChÝnh X¸c

[TextTitle_18]
Left=10
Top=303
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=NÐ Tr¸nh

[TextTitle_19]
Left=10
Top=319
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Ch¹y

[TextTitle_20]
Left=10
Top=336
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=C«ng KÝch

[TextTitle_21]
Left=10
Top=353
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=TiÒm N¨ng

[TextTitle_22]
Left=154
Top=287
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Phßng Thñ

[TextTitle_23]
Left=154
Top=303
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Kh¸ng B¨ng

[TextTitle_24]
Left=154
Top=319
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Kh¸ng L«i

[TextTitle_25]
Left=154
Top=336
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Kh¸ng Háa

[TextTitle_26]
Left=154
Top=353
Width=60
Height=15
Font=12
Color=255,255,255
MultiLine=0
Text=Kh¸ng §éc

;ÊäÈëÇ©Ãû
[SignInput]
Left=6
Top=88
Width=233
Height=15
Font=12
Type=2
MultiLine=0
MaxLen=31
Color=254,255,160
FocusBKColor=25,31,11
FocusBKColorAlpha=180
FocusNoCanBKColor=97,2,0
FocusNoCanBKColorAlpha=150

[InputBack]
Left=4
Top=86
Width=237
Height=19
Trans=1
Image=\spr\Ui4\Ö÷½çÃæ\½ÇÉ«ÐÅÏ¢×ÊÔ´\ÐÄÇéÊäÈë¿ò.spr

;·¢±íÇ©Ãû°´Å¥
[SummitSign]
Left=244
Top=86
Width=46
Height=19
Trans=0
Up=0
Down=2
Over=1
OverFrame=3
DisableFrame=3
Tip=V¨n tù ph¸t biÓu t©m t×nh
Label=Y kiÕn
Font=12
LabelYOffset=3
Color=169,211,190
OverColor=124,255,125
SelectColor=77,77,77
DisableColor=77,77,77
Image=\spr\Ui4\common\Ð¡°´Å¥¶þ×Ö.spr

[SignText]
Left=2
Top=109
Width=290
Height=47
RowInterval=3
Font=12
Selable=1
MaxMsgCount=3
MsgColor=255,217,78
SelColor=255,253,122
SelBgColor=77,77,77

[DelSignButton]
Left=0
Top=0
Width=9
Height=9
Color=0,255,0
Up=0
Down=1
Over=2
Tip=Xãa dßng nµy
Image=\spr\Ui4\Ö÷½çÃæ\½ÇÉ«ÐÅÏ¢×ÊÔ´\¹Ø±ÕÐ¡°´Å¥.spr

;¹«¿ªÏêÏ¸ÐÅÏ¢°´Å¥
Hide=0
[PublicCheckBox]
Left=10
Top=375
Width=150
Height=14
Trans=0
Up=0
Down=1
Over=1
Font=14
Label=C«ng khai thuéc tÝnh cña ta
Color=169,211,190
OverColor=124,255,125
OverBorderColor=77,77,77
SelectColor=77,77,77
DisableColor=77,77,77
;;;;;;;;;;;;;ÒÔÏÂ¶¨Òå×´Ì¬Í¼Æ¬µÄÒ»Ð©ÊôÐÔ
LabelImageOffset=0
ImageAlignRight=0
StatusEnableFrame=0
StatusDisableFrame=1
StatusInvalidFrame=2
StatusImgType=2
ImageWidth=14
ImageHeight=14
InitCheckStatus=0
StatusImage=\spr\Ui4\common\¹´Ñ¡.spr

;½çÃæÉèÖÃÖµ
[Settings]
BGBorderColor=100,80,30
BGSpriteColor=243,194,70
BGPurpleColor=188,40,255
BGPurpleBorder=100,80,123
BGPlatinaBorder=110,110,110
BGPlatinaColor=240,240,240

Left=0
Top=0
Width=0
Height=0
[ViewAttrib]
Left=180
Top=370
Width=120
Height=14
Trans=0
Up=0
Down=1
Over=2
Tip=Xem c¸c thuéc tÝnh kh¸c
Label=Thuéc tÝnh kh¸c
Font=14
LabelYOffset=3
Color=169,211,190
OverColor=124,255,125
SelectColor=77,77,77
DisableColor=77,77,77