; --------------------------------------------------------
; ÎÄ¼þÃû£º
; ¹¦ÄÜ ÈËÎï×´Ì¬×°±¸´°¿Ú_Íæ¼Ò×°±¸×ÓÒ³
; --------------------------------------------------------

;ÄÐ±³¾°
[Male]
Left=4
Top=49
Width=294
Height=394
Moveable=0
Trans=0
Image=\spr\Ui4\Ö÷½çÃæ\½ÇÉ«ÐÅÏ¢×ÊÔ´\×°±¸ÄÐ201910.spr
;StartPos=-430,100

;Å®±³¾°
[Female]
Left=4
Top=49
Width=294
Height=394
Moveable=0
Trans=0
Image=\spr\Ui4\Ö÷½çÃæ\½ÇÉ«ÐÅÏ¢×ÊÔ´\×°±¸Å®201910.spr
;StartPos=-430,100

;²»±äµÄ×Ö·û±êÇ©
[TitleText_0]
Left=1
Top=6
Width=40
Height=15
Font=12
HAlign=1
VAlign=1
Color=255,255,255
Text=Tªn

;PKÖµ
[TitleText_1]
Left=189
Top=6
Width=36
Height=15
Font=12
HAlign=1
VAlign=1
Color=255,255,255
Text=TrÞ PK:

;Ã±×Ó
[TitleText_2]
Left=108
Top=57
Width=56
Height=56
Font=12
HAlign=1
VAlign=1
MultiLine=1
Color=15,50,30
Text=§Ønh M¹o

;ÎäÆ÷
[TitleText_3]
Left=195
Top=125
Width=56
Height=108
Font=12
HAlign=1
VAlign=1
Color=15,50,30
Text=Vò khÝ 

;²±×Ó´÷µÄ
[TitleText_4]
Left=195
Top=87
Width=56
Height=30
Font=12
HAlign=1
VAlign=1
Color=15,50,30
Text=H¹ng Liªn

;Ãæ¾ß
[TitleText_5]
Left=46
Top=56
Width=24
Height=30
Font=12
HAlign=1
VAlign=1
Color=15,50,30
Text=MÆt n¹ 
MultiLine=1

;ÊÖïí
[TitleText_6]
Left=44
Top=94
Width=30
Height=56
Font=12
HAlign=1
VAlign=1
MultiLine=1
Color=15,50,30
Text=Hé uyÓn

;ÒÂ·þ
[TitleText_7]
Left=108
Top=120
Width=56
Height=82
Font=12
HAlign=1
VAlign=1
Color=15,50,30
Text=Y Phôc

;Ñü´ø
[TitleText_8]
Left=108
Top=210
Width=56
Height=30
Font=12
HAlign=1
VAlign=1
Color=15,50,30
Text=Th¾t l­ng

;½äÖ¸1
[TitleText_9]
Left=44
Top=158
Width=30
Height=30
Font=12
HAlign=1
VAlign=1
Color=15,50,30
Text=NhÉn

;½äÖ¸2
[TitleText_10]
Left=44
Top=196
Width=30
Height=30
Font=12
HAlign=1
VAlign=1
Color=15,50,30
Text=NhÉn

;ÊÎ×º
[TitleText_11]
Left=44
Top=234
Width=30
Height=56
Font=12
HAlign=1
VAlign=1
MultiLine=1
Color=15,50,30
Text=Ngäc béi

;Ð¬
[TitleText_12]
Left=195
Top=241
Width=56
Height=56
Font=12
HAlign=1
VAlign=1
MultiLine=1
Color=15,50,30
Text=Ngoa tö 

;Âí
[TitleText_13]
Left=108
Top=248
Width=56
Height=82
Font=12
HAlign=1
VAlign=1
Color=15,50,30
Text=Ngùa

;Åû·ç
[TitleText_14]
Left=44
Top=302
Width=30
Height=30
Font=12
HAlign=1
VAlign=1
MultiLine=1
Color=15,50,30
Text=Phi Phong

;Ó¡¼ø
[TitleText_15]
Left=188
Top=302
Width=30
Height=30
Font=12
HAlign=1
VAlign=1
Color=15,50,30
Text=Ên

;ÊÎÆ·
[TitleText_16]
Left=226
Top=302
Width=30
Height=30
Font=12
HAlign=1
VAlign=1
MultiLine=1
Color=15,50,30
Text=Trang Søc

;Õ½Ó¡
[TitleText_17]
Left=193
Top=53
Width=30
Height=30
Font=12
HAlign=1
VAlign=1
MultiLine=1
Color=15,50,30
Text=Ên ChiÕn

; ;ÃÅÅÉ¹Ò¼þ
; [TitleText_18]
; Left=230
; Top=53
; Width=30
; Height=30
; Font=12
; HAlign=1
; VAlign=1
; Color=15,50,30
; Text=¹ÒÊÎ

;ÐÕÃû
[Name]
Left=42
Top=6
Width=132
Height=15
Font=12
HAlign=1
Color=255,217,78

;PKÖµ
[PKValue]
Left=229
Top=6
Width=58
Height=15
Font=12
HAlign=1
Color=255,217,78

;×ªÉú
[TransLife]
Left=10
Top=20
Width=140
Height=15
Font=12
HAlign=0
Color=255,217,78

;Ç¿»¯×ÜµÈ¼¶
[EnchanceLevel]
Left=160
Top=20
Width=140
Height=15
Font=12
HAlign=0
Color=255,217,78

;×ÚÊ¦µÈ¼¶
[ZongShiLevel]
Left=160
Top=38
Width=140
Height=15
Font=12
HAlign=0
Color=255,217,78

;ÐÞÎªµãÊý
[XiuWeiPoint]
Left=10
Top=38
Width=140
Height=15
Font=12
HAlign=0
Color=255,217,78

;Ã±×Ó
[Cap]
Left=109
Top=57
Width=56
Height=56
HaveBgColor=0

;ÎäÆ÷
[Weapon]
Left=195
Top=125
Width=56
Height=108
HaveBgColor=0

;²±×Ó´÷µÄ
[Necklace]
Left=195
Top=87
Width=56
Height=30
HaveBgColor=0

;Ãæ¾ß
[Mask]
Left=46
Top=56
Width=30
Height=30
HaveBgColor=0

;Ãæ¾ßÍâ¹Û¿ª¹Ø
[MaskFeature]
Left=80
Top=59
Width=12
Height=12
Trans=0
Up=0
Down=1
Over=0
CheckBox=1
CheckOver=1
Image=\spr\Ui3\ÏµÍ³Ñ¡Ïî\¶©ÔÄ´ò¹´°´Å¥.spr
Tip=HiÓn thÞ ngo¹i quan mÆt n¹
;ÊÖïí
[Bangle]
Left=46
Top=94
Width=30
Height=56
HaveBgColor=0

;ÒÂ·þ
[Cloth]
Left=109
Top=120
Width=56
Height=82
HaveBgColor=0

;Ñü´ø
[Sash]
Left=109
Top=210
Width=56
Height=30
HaveBgColor=0

;½äÖ¸1
[Ring1]
Left=46
Top=158
Width=30
Height=30
HaveBgColor=0

;½äÖ¸2
[Ring2]
Left=46
Top=196
Width=30
Height=30
HaveBgColor=0

;ÊÎ×º
[Pendant]
Left=46
Top=234
Width=30
Height=56
HaveBgColor=0

;Ð¬
[Shoes]
Left=195
Top=241
Width=56
Height=56
HaveBgColor=0

;Âí
[Horse]
Left=109
Top=248
Width=56
Height=82
HaveBgColor=0

;Åû·ç
[Mantle]
Left=46
Top=302
Width=30
Height=30
HaveBgColor=0

;Ó¡¼ø
[Signet]
Left=191
Top=302
Width=30
Height=30
HaveBgColor=0

;ÊÎÆ·
[Shipin]
Left=227
Top=302
Width=30
Height=30
HaveBgColor=0

;Ó¡¼ø
[Seal]
Left=193
Top=49
Width=30
Height=30
HaveBgColor=0

; ;ÃÅÅÉ¹Ò¼þ
; [FactionPendant]
; Left=230
; Top=49
; Width=30
; Height=30
; HaveBgColor=0

; ;¹Ò¼þÍâ¹Û¿ª¹Ø
; [PendantFeature]
; Left=264
; Top=62
; Width=12
; Height=12
; Trans=0
; Up=0
; Down=1
; Over=0
; CheckBox=1
; CheckOver=1
; Image=\spr\Ui3\ÏµÍ³Ñ¡Ïî\¶©ÔÄ´ò¹´°´Å¥.spr
; Tip=ÏÔÊ¾¹ÒÊÎÍâ¹Û

;¼ÓËø½âËø°´Å¥
[BtnLock]
Left=35
Top=345
Width=67
Height=19
Font=14
HAlign=1
VAlign=1
LabelYOffset=3
Color=218,255,165
BorderColor=23,68,0
SelectColor=255,253,122
SelectBorderColor=255,0,0
OverColor=0,255,0
Up=1
Down=0
CheckBox=1
Image=\spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr
Label=Khãa

;ÎïÆ·°ó¶¨°´Å¥
[BtnBind]
Left=113
Top=345
Width=67
Height=19
Font=14
HAlign=1
VAlign=1
LabelYOffset=3
Color=218,255,165
BorderColor=23,68,0
SelectColor=255,253,122
SelectBorderColor=255,0,0
OverColor=0,255,0
Up=0
Down=1
Over=2
OverFrame=2
Image=\spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr
Label=§Ýnh

;×°±¸Ëø»ê°´Å¥
[BtnUnBind]
Left=191
Top=345
Width=67
Height=19
Font=14
HAlign=1
VAlign=1
LabelYOffset=3
Color=218,255,165
BorderColor=23,68,0
SelectColor=255,253,122
SelectBorderColor=255,0,0
OverColor=0,255,0
Up=0
Down=1
Over=2
OverFrame=2
Image=\spr\Ui4\common\Ð¡°´Å¥ËÄ×Ö.spr
Label=Th¸o

[ClothesWndBtn]
Left=3
Top=368
Width=70
Height=20
Font=12
Color=0,255,0
HAlign=1
VAlign=1
LabelYOffset=4
Color=169,211,190
OverColor=169,211,190
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=2
Over=0
Trans=0
Image=\spr\Ui3\°ï»á½çÃæ\Í¨ÓÃ°´Å¥5×Ö°æ.spr
Label=Ngo¹i trang

[BtnStrength]
Left=75
Top=368
Width=70
Height=20
Font=12
Color=0,255,0
HAlign=1
VAlign=1
LabelYOffset=3
Color=169,211,190
OverColor=169,211,190
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=2
Over=0
Trans=0
Image=\spr\Ui3\°ï»á½çÃæ\Í¨ÓÃ°´Å¥5×Ö°æ.spr
Label=C­êng hãa

[BtnJueXue]
Left=147
Top=368
Width=70
Height=20
Font=12
Color=0,255,0
HAlign=1
VAlign=1
LabelYOffset=3
Color=169,211,190
OverColor=169,211,190
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=2
Over=0
Trans=0
Image=\spr\Ui3\°ï»á½çÃæ\Í¨ÓÃ°´Å¥5×Ö°æ.spr
Label=TuyÖt Häc

[BtnZongShi]
Left=220
Top=368
Width=70
Height=20
Font=12
Color=0,255,0
HAlign=1
VAlign=1
LabelYOffset=3
Color=169,211,190
OverColor=169,211,190
SelectColor=124,255,125
DisableColor=77,77,77
Up=0
Down=2
Over=0
Trans=0
Image=\spr\Ui3\°ï»á½çÃæ\Í¨ÓÃ°´Å¥5×Ö°æ.spr
Label=T«ng s­ 

;½çÃæÉèÖÃÖµ
[Settings]
BGBorderColor=100,80,30
BGSpriteColor=243,194,70
BGPurpleColor=188,40,255
BGPurpleBorder=100,80,123
BGPlatinaBorder=110,110,110
BGPlatinaColor=240,240,240