if MODEL_GAMESERVER == 1 then
	Include("\\script\\script_protocol\\protocol_def_gs.lua")
elseif MODEL_GAMECLIENT == 1 then
	Include("\\script\\script_protocol\\protocol_def_c.lua")
end

T_PROTOCOL_DEF = T_PROTOCOL_DEF or {}

ScriptProtocol = {}

ScriptProtocol.KE_SCRIPT_PROTOCOL = 
{
	"emSCRIPT_PROTOCOL_ECHO",
	"emSCRIPT_PROTOCOL_EQUIP_RANK",
	-- "emSCRIPT_PROTOCOL_CLIENT_CMD",
	"emSCRIPT_PROTOCOL_STORES_REQUEST_ITEM",
	"emSCRIPT_PROTOCOL_REQUESTTABLE",
	"emSCRIPT_PROTOCOL_BATTLE",
	"emSCRIPT_PROTOCOL_BINGO_MACHINE",
	"emSCRIPT_PROTOCAL_HuoYueDu_Award", --给活跃度奖励	
	"emSCRIPT_PROTOCOL_COUNT",
	"emSCRIPT_PROTOCOL_BINGO_OPENWINDOW",
	"emSCRIPT_PROTOCOL_BINGO_COIN",
	"emSCRIPT_PROTOCOL_BINGO_GET_AWARD_RESULT",
	"emSCRIPT_PROTOCOL_BINGO_GET_COIN",
	
	"emSCRIPT_PROTOCOL_OPEN_CREDITS_SHOP",
	"emSCRIPT_PROTOCOL_SIGNUP_AREAN",
	"emSCRIPT_PROTOCOL_QIANCHONGLOU",
	"emSCRIPT_PROTOCOL_OPEN_JIAOZI_SHOP",
	"emSCRIPT_PROTOCOL_FULI_REPORT",
	"emSCRIPT_PROTOCOL_SECURITY_LOCK",
	"emSCRIPT_PROTOCOL_SECURITY_UNLOCK",
	"emSCRIPT_PROTOCOL_SECURITY_CONFIG",
	"emSCRIPT_PROTOCOL_SECURITY_RESET",
	"emSCRIPT_PROTOCOL_LUCKY_TURNTABLE",
	"emSCRIPT_PROTOCOL_POP_BLACK_TIPS",
	"emSCRIPT_PROTOCOL_OFFLINE",
	"emSCRIPT_PROTOCOL_ONLINE_AWARD",
	"emSCRIPT_PROTOCOL_CLIENT_EVENT",
	"emSCRIPT_PROTOCOL_ACHIEVEMENT_REWARD",
	"emSCRIPT_PROTOCOL_ACHIEVEMENT_ACHIEVED",
	"emSCRIPT_PROTOCOL_TONG_GUTA",
	---------------------签到系统 Begin--------------------------
	"emSCRIPT_PROTOCAL_SIGNIN_FETCH_DATA",
	"emSCRIPT_PROTOCAL_SIGNIN_DO",
	"emSCRIPT_PROTOCAL_SIGNIN_AWARD",
	"emSCRIPT_PROTOCAL_SIGNIN_SYNC_DATE",
	"emSCRIPT_PROTOCAL_SIGNIN_SYNC_AWARD",
	---------------------签到系统 End--------------------------
	"emSCRIPT_PROTOCOL_TONG_PKMESSAGE",
	---------------------披风系统(镶嵌) Begin--------------------------
	"emSCRIPT_PROTOCOL_MANTLE_OPENUI",  -- S2C
	"emSCRIPT_PROTOCOL_MANTLE_DOINLAY", -- C2S
	"emSCRIPT_PROTOCOL_MANTLE_INLAYRESULT",
    ---------------------披风系统(镶嵌) End--------------------------
    ---------------------宠物系统Begin--------------------------
	"emSCRIPT_PROTOCOL_PET_SKILL_LEARN",  -- c2C
	"emSCRIPT_PROTOCOL_PET_SKILL_BIND", -- C2S
	"emSCRIPT_PROTOCOL_PET_UPGRADE", -- C2S
	"emSCRIPT_PROTOCOL_PET_RENAME", -- C2S
	"emSCRIPT_PROTOCOL_PET_EXP", -- C2S
	"emSCRIPT_PROTOCOL_PET_SUMMON", -- C2S
	"emSCRIPT_PROTOCOL_PET_UNSUMMON", -- C2S
	"emSCRIPT_PROTOCOL_PET_FUSION", -- C2S
	"emSCRIPT_PROTOCOL_PET_SKILL_UPGRADE",
	"emSCRIPT_PROTOCOL_OPEN_PET",-- C2S
	"emSCRIPT_PROTOCOL_PET_PASSIVE_SKILL_LEARN",-- C2S
	"emSCRIPT_PROTOCOL_PET_PASSIVE_SKILL_UPGRADE",-- C2S

    ---------------------宠物系统End--------------------------
	---------------------外装盒子 Begin--------------------------
    "emSCRIPT_PROTOCOL_NEW_CLOTHES_SHOP",
    "emSCRIPT_PROTOCOL_NEW_CLOTHES_WARDROBE",
    ---------------------外装盒子 End--------------------------
    ---------------------以物换物通用商店 Begin--------------------------
    "emSCRIPT_PROTOCOL_EXCHANGE_SHOP",
    ---------------------以物换物通用商店 End--------------------------

	"emSCRIPT_PROTOCOL_UPDATE_CLOTH_ENCHANTING_UI",
	"emSCRIPT_PROTOCOL_TRY_ENCHANTING",
	"emSCRIPT_PROTOCOL_ENCHANTING_LEVELUP",
	---------------------新野叟任务-------------------------
	"emSCRIPT_PROTOCOL_REQUEST_YESOU_TASK_DESC",
	"emSCRIPT_PROTOCOL_RESPONSE_YESOU_TASK_DESC",

	-------------------------新五行印---------------------------
	"emSCRIPT_PROTOCOL_C2S_SS_CONSUME_MSG",
	"emSCRIPT_PROTOCOL_S2C_SS_CONSUME_MSG",

	"emSCRIPT_PROTOCOL_S2C_SS_OPEN_MAIN_WINDOW",

	"emSCRIPT_PROTOCOL_C2S_SS_MAKE",

	"emSCRIPT_PROTOCOL_C2S_SS_RANDOM_BASE_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_SS_RANDOM_BASE_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_SS_APPLY_BASE_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_SS_APPLY_BASE_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_SS_CANCLE_BASE_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_SS_CANCLE_BASE_ATTRIB",

	"emSCRIPT_PROTOCOL_C2S_SS_ENGRAVE",
	"emSCRIPT_PROTOCOL_S2C_SS_ENGRAVE",

	"emSCRIPT_PROTOCOL_C2S_SS_UPGRADE",
	"emSCRIPT_PROTOCOL_S2C_SS_UPGRADE",

	"emSCRIPT_PROTOCOL_C2S_SS_ACTIVATE",
	"emSCRIPT_PROTOCOL_S2C_SS_ACTIVATE",

	"emSCRIPT_PROTOCOL_C2S_SS_RANDOM_IMPLICIT_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_SS_RANDOM_IMPLICIT_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_SS_APPLY_IMPLICIT_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_SS_APPLY_IMPLICIT_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_SS_CANCLE_IMPLICIT_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_SS_CANCLE_IMPLICIT_ATTRIB",

	"emSCRIPT_PROTOCOL_C2S_SS_REBUILD",
	"emSCRIPT_PROTOCOL_S2C_SS_REBUILD",
	-----------------------------------------------------------

	-------------------月度充值-----------------------------
	"emSCRIPT_PROTOCOL_S2C_UPDATE_MONTHLYRECHARGE",
	"emSCRIPT_PROTOCOL_C2S_MONTHLYRECHARGE_TAKEDAILYAWARD",
	"emSCRIPT_PROTOCOL_C2S_MONTHLYRECHARGE_TAKEAWARD",
	"emSCRIPT_PROTOCOL_C2S_MONTHLYRECHARGE_SYNC",
	"emSCRIPT_PROTOCOL_C2S_MONTHLYRECHARGE_BIND",
	-------------------------------------------------------
	
	------------------黄金boss战报-------------------------
	"emSCRIPT_PROTOCOL_C2S_GOLDBOSSREPORT_SYNCDATA",
	"emSCRIPT_PROTOCOL_S2C_GOLDBOSSREPORT_SYNCDATA",
	"emSCRIPT_PROTOCOL_S2C_GOLDBOSSREPORT_NODATA",
	-------------------------------------------------------

	------------------------邮箱系统---------------------------
    -- S2C
    "emSCRIPT_PROTOCOL_MAIL_HEADERLIST",
    "emSCRIPT_PROTOCOL_MAIL_NEWMAIL",
    "emSCRIPT_PROTOCOL_MAIL_STATECHANGE",
    "emSCRIPT_PROTOCOL_MAIL_DELETE",
    "emSCRIPT_PROTOCOL_MAIL_WHOLEMAIL",
    "emSCRIPT_PROTOCOL_MAIL_OPENWINDOW",
    -- C2S
    "emSCRIPT_PROTOCOL_MAIL_REQUEST_HEADERLIST",
    "emSCRIPT_PROTOCOL_MAIL_REQUEST_DELETE",
    "emSCRIPT_PROTOCOL_MAIL_REQUEST_WHOLEMAIL",
    "emSCRIPT_PROTOCOL_MAIL_REQUEST_STATECHANGE",
	"emSCRIPT_PROTOCOL_MAIL_REQUEST_AUTODELETE",
	
		-------------------决战巅峰----------------------------------
	"emSCRIPT_PROTOCOL_S2C_JZDF_ENTER",
	"emSCRIPT_PROTOCOL_S2C_JZDF_LEAVE",
	"emSCRIPT_PROTOCOL_S2C_JZDF_UPDATE",
	"emSCRIPT_PROTOCOL_S2C_JZDF_OPEN_URL",
		-----------------------2020过年活动---------------------------
	"emSCRIPT_PROTOCOL_S2C_OPENNEWYEARENTRANCE2020",
	"emSCRIPT_PROTOCOL_C2S_NEWYEARLOTTERY2020_SYNCSCROLL",
	"emSCRIPT_PROTOCOL_S2C_NEWYEAR_SETLOTTERYSCROLL",
	"emSCRIPT_PROTOCOL_C2S_NEWYEARLOTTERY2020_SYNCLOTTERY",
	"emSCRIPT_PROTOCOL_S2C_NEWYEAR_SETLOTTERYDATA",
	"emSCRIPT_PROTOCOL_C2S_NEWYEARLOTTERY2020_GETAWARD",
	"emSCRIPT_PROTOCOL_C2S_NEWYEARLOTTERY2020_GETPLAYERDATA",
	------------------------披风洗练--------------------------
	"emSCRIPT_PROTOCOL_S2C_MANTLE_OPEN_IMPLICIT_WINDOW",
	"emSCRIPT_PROTOCOL_C2S_MANTLE_IMPLICIT_CONSUME_MSG",
	"emSCRIPT_PROTOCOL_S2C_MANTLE_IMPLICIT_CONSUME_MSG",
	"emSCRIPT_PROTOCOL_C2S_MANTLE_IMPLICIT_RANDOM_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_MANTLE_IMPLICIT_RANDOM_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_MANTLE_IMPLICIT_APPLY_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_MANTLE_APPLY_IMPLICIT_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_MANTLE_IMPLICIT_CANCLE_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_MANTLE_CANCLE_IMPLICIT_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_MANTLE_IMPLICIT_ACTIVATE",
	"emSCRIPT_PROTOCOL_S2C_MANTLE_IMPLICIT_ACTIVATE",
	---------------------英雄塔Ui Begin----------------------------------------
	"emSCRIPT_PROTOCOL_TOGGLE_TOWERTASKBTN",
	"emSCRIPT_PROTOCOL_TOGGLE_TOWERTASK",
	"emSCRIPT_PROTOCOL_TOWERTASK_SETACCEPT",
	"emSCRIPT_PROTOCOL_TOWERTASK_SETTASK",
	"emSCRIPT_PROTOCOL_TOWERTASK_SETTIMER",
	"emSCRIPT_PROTOCOL_TOWERTASK_ADDTARGET",
	"emSCRIPT_PROTOCOL_TOWERTASK_ADDTARGETCOUNT",
	"emSCRIPT_PROTOCAL_TOWERTASK_START",
	"emSCRIPT_PROTOCAL_TOWERTASK_AWARD",
	"emSCRIPT_PROTOCAL_TOWERTASK_LEAVE",
	
	"emSCRIPT_PROTOCOL_HTLISTQUERYOTHER_DATA",
	"emSCRIPT_PROTOCOL_HTLISTClOSE",
	"emSCRIPT_PROTOCOL_HTLISTOPEN",
	"emSCRIPT_PROTOCOL_HTLISTOLDSETDATA",
	"emSCRIPT_PROTOCOL_HTLISTOLDdELDATA",
	"emSCRIPT_PROTOCOL_HTLISTOLDDELDATAS",
	"emSCRIPT_PROTOCOL_HTLISTNOWSETDATA",
	"emSCRIPT_PROTOCOL_HTLISTNOWSETMINEDATA",
	"emSCRIPT_PROTOCOL_HTLISTNOWDELDATA",
	"emSCRIPT_PROTOCOL_HTLISTNOWDELDATAS",
	"emSCRIPT_PROTOCOL_OPENWNDFLIPS",
	"emSCRIPT_PROTOCOL_CLOSEWNDFLIPS",
	"emSCRIPT_PROTOCOL_WNDFLIPSPLAYSINGLE",
	"emSCRIPT_PROTOCOL_HTLISTQUERYOTHER",
	---------------------英雄塔Ui End------------------------------------------
	"emSCRIPT_PROTOCOL_S2C_JIANGHUJI_SYNC_INFO",
	"emSCRIPT_PROTOCOL_C2S_JIANGHUJI_GET_AWARD",
	
	---------------------门派挂件 End--------------------------
   	 "emSCRIPT_PROTOCOL_PENDANT_OPENUI",  -- S2C
  	 "emSCRIPT_PROTOCOL_PENDANT_DOINLAY", -- C2S
  	 "emSCRIPT_PROTOCOL_PENDANT_STONEDOWN", --C2S
  	 "emSCRIPT_PROTOCOL_PENDANT_INLAYRESULT",

 	 "emSCRIPT_PROTOCOL_PENDANT_OPENSCOURUI",  -- S2C
  	 "emSCRIPT_PROTOCOL_PENDANT_SCOUR", -- C2S
   	 "emSCRIPT_PROTOCOL_PENDANT_INLAYSCOURRESULT",

   	 "emSCRIPT_PROTOCOL_PENDANTRANK_REQUEST", --C2S
   	 "emSCRIPT_PROTOCOL_PENDANTRANK_RETURN", -- S2C

	---------------------门派挂件 End--------------------------
	---------------------新七城大战---------------------------
	"emSCRIPT_PROTOCAL_NEW_SEVEN_CITY_REPORT",
	--------------------拍卖行系统-----------------------
	-- S2C
	"emSCRIPT_PROTOCOL_AUCTION_OFFERPRICERET",
	"emSCRIPT_PROTOCOL_AUCTION_REFUNDRET",
	"emSCRIPT_PROTOCOL_AUCTION_ACTIVITYLIST",
	"emSCRIPT_PROTOCOL_AUCTION_ACTIVITYINFO",
	"emSCRIPT_PROTOCOL_AUCTION_ITEMINFO",
	"emSCRIPT_PROTOCOL_AUCTION_MEMBERLIST",
	"emSCRIPT_PROTOCOL_AUCTION_NEWACTIVITY",
	"emSCRIPT_PROTOCOL_AUCTION_ENDACTIVITY",
	"emSCRIPT_PROTOCOL_AUCTION_NEWITEM",
	"emSCRIPT_PROTOCOL_AUCTION_ENDITEM",
	"emSCRIPT_PROTOCOL_AUCTION_TPRICECHANGE",
	-- C2S
	"emSCRIPT_PROTOCOL_AUCTION_REQUEST_OFFERENGLISHPRICE",  -- 英式报价
	"emSCRIPT_PROTOCOL_AUCTION_REQUEST_OFFERDUTCHPRICE",    -- 荷式报价
	"emSCRIPT_PROTOCOL_AUCTION_REQUEST_REFUND",
	"emSCRIPT_PROTOCOL_AUCTION_REQUEST_ACTIVITYLIST",
	"emSCRIPT_PROTOCOL_AUCTION_REQUEST_ACTIVITYCONTENT",
	"emSCRIPT_PROTOCOL_AUCTION_REQUEST_ITEMCONTENT",
	"emSCRIPT_PROTOCOL_AUCTION_REQUEST_MEMBERLIST",
	"emSCRIPT_PROTOCOL_AUCTION_REQUEST_OPENSHOP",
	"emSCRIPT_PROTOCOL_AUCTION_REQUEST_GETBACKITEM",
	-------------------- 同伴装备 ---------------------
	"emSCRIPT_PROTOCOL_C2S_OPEN_COMPANIONEQUIP",
	"emSCRIPT_PROTOCOL_C2S_ASKCONSUME_COMPANIONEQUIP",
	"emSCRIPT_PROTOCOL_C2S_TYR_REBUILD_COMPANIONEQUIP",
	"emSCRIPT_PROTOCOL_S2C_TRYREBUILD_COMPANIONEQUIP",
	"emSCRIPT_PROTOCOL_C2S_DO_REBUILD_COMPANIONEQUIP",
	"emSCRIPT_PROTOCOL_S2C_REBUILD_COMPANIONEQUIP",
	"emSCRIPT_PROTOCOL_S2C_COMPANIONEQUIP_SETCOST_TIP",
	"emSCRIPT_PROTOCOL_S2C_COMPANIONEQUIP_DOREBUILD",
	---------------------- 联赛 ----------------------
	"emSCRIPT_PROTOCOL_S2C_LIANSAI_SYNCREPORTUI",
	"emSCRIPT_PROTOCOL_S2C_LIANSAI_CLOSEREPORTUI",
	"emSCRIPT_PROTOCOL_S2C_LIANSAI_SYNCTEAMLIST",
	"emSCRIPT_PROTOCOL_C2S_LIANSAI_SETGAMBLE",
	"emSCRIPT_PROTOCOL_C2S_LIANSAI_REFREASH",
	"emSCRIPT_PROTOCOL_S2C_LIANSAI_STARTFINAL",
	"emSCRIPT_PROTOCOL_C2S_LIANSAI_GOTOGAMBLE",
	"emSCRIPT_PROTOCOL_S2C_LIANSAI_CLOSEENTERANCE",
		--------------------新春签到-------------------------
	"emSCRIPT_PROTOCOL_S2C_SIGNACT_ENTRANCE",
	"emSCRIPT_PROTOCOL_S2C_SIGNACT_SYNCDATA",
	"emSCRIPT_PROTOCOL_C2S_SIGNACT_GET",

	------------------------绝学---------------------------
	"emSCRIPT_PROTOCOL_C2S_CHECK_CANOPEN_JUEXUE",
	"emSCRIPT_PROTOCOL_S2C_OPEN_JUEXUE",

	    --------------侠峰论剑--------------------
	"emScript_PROTOCOL_S2C_GREATTEAMFIGHT_SYNC",
	"emScript_PROTOCOL_C2S_GREATTEAMFIGHT_REQUEST",

	--------------------2021新商店---------------------------
    -- S2C
    "emSCRIPT_PROTOCOL_SHOP_2021_SEND_SERVER_INFO",
    -- C2S
    "emSCRIPT_PROTOCOL_SHOP_2021_REQUEST_BUY_ITEM",
    "emSCRIPT_PROTOCOL_SHOP_2021_REQUEST_SERVER_INFO",
	--------------------马隐藏属性---------------------------
	"emSCRIPT_PROTOCOL_C2S_HORSE_IMPLICIT_RANDOM_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_HORSE_IMPLICIT_ACTIVATE",
	"emSCRIPT_PROTOCOL_S2C_HORSE_IMPLICIT_ACTIVATE",
	"emSCRIPT_PROTOCOL_S2C_HORSE_IMPLICIT_RANDOM_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_HORSE_IMPLICIT_APPLY_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_HORSE_APPLY_IMPLICIT_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_HORSE_IMPLICIT_CANCLE_ATTRIB",
	"emSCRIPT_PROTOCOL_S2C_HORSE_CANCLE_IMPLICIT_ATTRIB",
	"emSCRIPT_PROTOCOL_C2S_HORSE_IMPLICIT_CONSUME_MSG",
	"emSCRIPT_PROTOCOL_S2C_HORSE_IMPLICIT_CONSUME_MSG",
	"emSCRIPT_PROTOCOL_S2C_HORSE_IMPLICIT_OPENUI",
	--------------------提示泡泡-----------------------
	"emSCRIPT_PROTOCOL_S2C_NOTICE_PAOPAO",
	--------------------同伴装备升级-----------------------
	"emSCRIPT_PROTOCOL_C2S_COMPANION_UPGRADE",
	"emSCRIPT_PROTOCOL_S2C_COMPANION_UPGRADE_UPDATE",
	----------------同步时间线-------------------
	"emScript_PROTOCOL_S2C_TIMELINE",
	----------------登陆领奖活动-------------------
	"emSCRIPT_PROTOCOL_S2C_LOGINAWARD2024",
	"emSCRIPT_PROTOCOL_C2S_LOGINAWARD2024",
	----------------宗师技能-------------------
	"emSCRIPT_PROTOCOL_S2C_MASTER_SKILL_UPDATE_WND",

	"emSCRIPT_PROTOCOL_C2S_MASTER_SKILL_ACTIVE",
	"emSCRIPT_PROTOCOL_C2S_MASTER_SKILL_EXCHANGE_XIUWEI",
	"emSCRIPT_PROTOCOL_C2S_MASTER_SKILL_UPGRADE_SKILL",
	"emSCRIPT_PROTOCOL_C2S_MASTER_SKILL_RESET_ALL_SKILL",
	"emSCRIPT_PROTOCOL_C2S_MASTER_SKILL_GET_RANK_TOP10"
}

function ScriptProtocol:_InitProtocolEnum()
	for key, v in self.KE_SCRIPT_PROTOCOL do
		self[v] = key
	end
end

function ScriptProtocol:RegProtocol(szProtocolEnum, szFile, szFun, tbParamFormat)
	self.tbProtocolDef = self.tbProtocolDef or {}
	local nProtocolId =  self[szProtocolEnum]
	if type(nProtocolId) ~= "number" then
		print("reg script protocol fail because it's nil"..szProtocolEnum)
		return
	end
	if self.tbProtocolDef[nProtocolId] then
		error("reg script protocol fail because reged "..(self.KE_SCRIPT_PROTOCOL[nProtocolId] or "nil"))
		return
	end
	self.tbProtocolDef[nProtocolId] = {szFile, szFun, tbParamFormat}
end

function ScriptProtocol:HandleProcess(nHandle, tbParamFormat)
	if type(tbParamFormat) ~= "table" then
		return {nHandle}
	end
	local tbParam = {}
	for i=1, getn(tbParamFormat) do
		local var = ObjBuffer:PopByType(nHandle, tbParamFormat[i])
		tinsert(tbParam, var)
	end
	return tbParam
end


--服务器收到的协议, 服务器处理
function ScriptProtocol:ProtocolProcess(nProtolId, nHandle)	
	if type(nProtolId) == "number" and type(self.tbProtocolDef[nProtolId]) == "table" then
		local szFile = self.tbProtocolDef[nProtolId][1]
		local szFun = self.tbProtocolDef[nProtolId][2]
		local tbParamFormat = self.tbProtocolDef[nProtolId][3]
		local tbParam = self:HandleProcess(nHandle, tbParamFormat)
		if MODEL_GAMESERVER == 1 then
			DynamicExecuteByPlayer(PlayerIndex, szFile, szFun, unpack(tbParam))
		elseif MODEL_GAMECLIENT == 1 then
			DynamicExecute(szFile, szFun, unpack(tbParam))
		end
	end
end

function ScriptProtocol:RegProtocolSet()
	for i=1, getn(T_PROTOCOL_DEF) do 
		local tb = T_PROTOCOL_DEF[i]
		if tb then
			self:RegProtocol(unpack(tb))
		end
	end
end

function ScriptProtocol:SendData(szEnum, nHandle)
	if (type(self[szEnum]) == "number") then
		if MODEL_GAMESERVER == 1 then
			SendScriptData(self[szEnum], nHandle)
		elseif MODEL_GAMECLIENT == 1 then
			SendScriptDataToServer(self[szEnum], nHandle)
		end
	end
end

ScriptProtocol:_InitProtocolEnum()
ScriptProtocol:RegProtocolSet()

